// Define high-quality, consistent SVG flags for all languages.
const syrianOppositionFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzAwN2EzZCIvPjxyZWN0IHk9IjIwMCIgd2lkdGg9IjkwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiNmZmYiLz48cmVjdCB5PSI0MDAiIHdpZHRoPSI5MDAiIGhlaWdodD0iMjAwIiBmaWxsPSIjMDAwIi8+PGcgZmlsbD0iI2NlMTEyNiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDUwIDMwMCkgc2NhbGUoMjIpIj48ZyBpZD0icyI+PHBhdGggZD0iTTAtMi4zNzc1bDEuNTQ1IDQuNzU1LTQuMDcyLTIuOTM5aDUuMDU0TC0xLjU0NSAyLjM4eiIvPjwvZz48dXNlIGhyZWY9IiNzIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTIpIi8+PHVzZSBocmVmPSIjcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCkiLz48dXNlIGhyZWY9IiNzIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMikiLz48L2c+PC9zdmc+" alt="Syrian Flag">`;
const germanFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1IDMiPjxyZWN0IHdpZHRoPSI1IiBoZWlnaHQ9IjEiIHk9IjAiIGZpbGw9IiMwMDAiLz48cmVjdCB3aWR0aD0iNSIgaGVpZ2h0PSIxIiB5PSIxIiBmaWxsPSIjRDAwIi8+PHJlY3QgeT0iMiIgd2lkdGg9IjUiIGhlaWdodD0iMSIgZmlsbD0iI0ZGQ0UwMCIvPjwvc3ZnPg==" alt="German Flag">`;
const turkishFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI2UzMGExNyIvPjxjaXJjbGUgY3g9IjI3NSIgY3k9IjMwMCIgcj0iMTUwIiBmaWxsPSIjZmZmIi8+PGNpcmNsZSBjeD0iMzEyLjUiIGN5PSIzMDAiIHI9IjEyMCIgZmlsbD0iI2UzMGExNyIvPjxwYXRoIGQ9Ik00MjUgMzAwbDExOS41LTM2LjctNzMuOSA5Ni4xVjI0MC42bC03My45IDk2LjF6IiBmaWxsPSIjZmZmIi8+PC9zdmc+" alt="Turkish Flag">`;
const ukrainianFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MDAgNDAwIj48cmVjdCB3aWR0aD0iNjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzAwNUJCQiIvPjxyZWN0IHk9IjIwMCIgd2lkdGg9IjYwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiNGRkQ1MDAiLz48L3N2Zz4=" alt="Ukrainian Flag">`;

export const translations = {
  ar: {
    langName: `${syrianOppositionFlagImg} العربية`,
    dir: "rtl",
    headerTitle: "توجيه مهني مع Ahmad Mrashaha",
    footerText: "© 2025 - تم التطوير بواسطة Ahmad Mrashaha لمساعدتك في العثور على طريقك.",
    welcomeTitle: "اكتشف مسارك المهني المثالي في ألمانيا",
    welcomeDesc: "أجب على 30 سؤالاً دقيقاً حول شخصيتك، مهاراتك، وطموحاتك. سيقوم الذكاء الاصطناعي لدينا بتحليل إجاباتك بعمق لاقتراح أفضل المسارات المهنية، التدريب المهني (Ausbildung)، أو المسارات الدراسية لك.",
    startQuiz: "ابدأ اختبار التوجيه المهني",
    startQuizDesc: "أجب على أسئلتنا المصممة خصيصًا واحصل على تحليل شخصي لمسارك المهني.",
    browseProfessions: "تصفح المهن",
    browseProfessionsDesc: "استكشف قاعدة بياناتنا للمهن والتدريب المهني والمسارات الدراسية.",
    careerPathVideos: "شاهد فيديوهات المهن",
    careerPathVideosDesc: "تعرف على المزيد حول المهن المختلفة من خلال مشاهدة مقاطع فيديو قصيرة.",
    careerPathVideosTitle: "فيديوهات المسار المهني",
    careerPathVideosDescPage: "تصفح مجموعتنا من مقاطع الفيديو لإلقاء نظرة واقعية على مختلف المهن.",
    searchAvailableJobs: "ابحث عن وظائف متاحة",
    searchAvailableJobsDesc: "ابحث عن فرص عمل حقيقية متاحة الآن في جميع أنحاء ألمانيا.",
    searchForPraktikum: "ابحث عن تدريب عملي (Praktikum)",
    searchForPraktikumDesc: "اعثر على فرص تدريب عملي وأنشئ رسائل بريد إلكتروني احترافية لتقديم طلبك.",
    professionsDesc: "ابحث وتصفح فرص العمل والتدريب المهني والدراسة الجامعية في ألمانيا.",
    back: "الخلف",
    next: "التالي",
    getResults: "احصل على نتائجي",
    loadingTitle: "جاري تحليل شخصيتك...",
    loadingDesc: "يقوم الذكاء الاصطناعي بإعداد تقريرك المهني المفصل. قد يستغرق هذا بضع لحظات.",
    resultsTitleFor: "تقريرك المهني لـ {name}",
    you: "لك",
    personalitySummary: "تحليل شخصيتك المهنية",
    recommendedPaths: "المسارات المهنية الموصى بها",
    careerAdvice: "نصائح مهنية مخصصة",
    restart: "العودة للرئيسية",
    searchPlaceholder: "ابحث عن مهنة...",
    all: "الكل",
    ausbildung: "تدريب مهني",
    study: "دراسة",
    job: "وظيفة",
    duration: "المدة",
    salary: "الراتب",
    requirements: "المتطلبات",
    duties: "الواجبات",
    home: "الرئيسية",
    errorText: "عذراً، حدث خطأ أثناء إنشاء نتائجك. يرجى المحاولة مرة أخرى لاحقاً.",
    answerHere: "اكتب إجابتك هنا...",
    page: "صفحة",
    printReport: "طباعة التقرير",
    emailReport: "إرسال عبر الإيميل",
    saveReport: "حفظ النتائج",
    reportSaved: "تم الحفظ!",
    emailSubject: "تقريري المهني من موقع توجيه مهني",
    jobSearchDesc: "استخدم الذكاء الاصطناعي للبحث عن وظائف أو فرص تدريب مهني متاحة حالياً في ألمانيا. أدخل المسمى الوظيفي والموقع للحصول على نتائج مباشرة.",
    jobTitlePlaceholder: "مثال: مطور برمجيات، ممرض...",
    locationPlaceholder: "مثال: برلين، هامبورغ...",
    search: "بحث",
    jobSearchLoading: "جاري البحث عن وظائف متاحة...",
    jobSearchSources: "عروض العمل المتاحة (المصادر)",
    jobSearchPrompt: "باستخدام بحث جوجل، ابحث عن وظائف أو فرص تدريب مهني (Ausbildung) متاحة حالياً لـ '{jobTitle}' في أو بالقرب من '{location}'، ألمانيا. لا تقدم ملخصًا. قدم فقط روابط المصدر الأصلية التي وجدتها.",
    noJobsFound: "لم يتم العثور على عروض عمل مطابقة.",
    savedReportsTitle: "التقارير المحفوظة",
    anonymousReport: "تقرير بدون اسم",
    viewDetails: "عرض التفاصيل",
    delete: "حذف",
    confirmDeleteReport: "هل أنت متأكد أنك تريد حذف هذا التقرير؟",
    noSavedReports: "لا يوجد تقارير محفوظة بعد.",
    adminLogin: "دخول المسؤول",
    responsibleLogin: "دخول المسؤول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صالحة.",
    logout: "تسجيل الخروج",
    praktikumDesc: "هل تبحث عن تدريب عملي (Praktikum)؟ أدخل المجال الذي تهتم به والمدينة، وسيقوم الذكاء الاصطناعي بالبحث عن شركات مناسبة لك. اختر واحدة، ثم أنشئ مسودة بريد إلكتروني احترافية للاستفسار.",
    fieldPlaceholder: "مثال: تكنولوجيا المعلومات، تسويق، هندسة...",
    yourNamePlaceholder: "اسمك الكامل",
    praktikumSearchBtn: "ابحث عن شركات",
    praktikumCompanyLoading: "جاري البحث عن فرص تدريب...",
    praktikumCompanyResult: "الشركات المقترحة",
    company: "الشركة",
    location: "الموقع",
    select: "اختر",
    selected: "تم الاختيار",
    praktikumGenerateEmailTitle: "أنشئ بريداً إلكترونياً للاستفسار",
    praktikumGenerateEmailBtn: "أنشئ البريد الإلكتروني",
    praktikumEmailLoading: "جاري كتابة بريدك الإلكتروني...",
    praktikumYourEmail: "مسودة بريدك الإلكتروني",
    copyEmail: "نسخ البريد الإلكتروني",
    copied: "تم النسخ!",
    praktikumSearchError: "عذراً، لم نتمكن من العثور على شركات مناسبة. الرجاء محاولة البحث بمصطلحات مختلفة.",
    praktikumSearchPrompt: "الدور: مستخرج بيانات دقيق. \nالتوجيه الأساسي: استخدم بحث جوجل للعثور على شركات لتدريب عملي في '{field}' في '{location}'، ألمانيا. \nالقاعدة الحاسمة 1: الدقة هي الأهم. يُمنع منعاً باتاً اختراع أو تخمين أو استنتاج أي معلومات. مصدرك الوحيد هو نتائج بحث جوجل المقدمة. إذا لم يتم العثور على معلومة (مثل رقم هاتف أو عنوان كامل) في نتائج البحث، يجب عليك استخدام سلسلة نصية فارغة \"\". \nالقاعدة الحاسمة 2: يجب أن تكون الاستجابة بأكملها عبارة عن مصفوفة JSON نظيفة وصالحة. لا تقم بتضمين أي نص توضيحي أو ملاحظات أو markdown مثل ```json. يجب أن تبدأ الاستجابة بـ [ وتنتهي بـ ]. \nمخطط الإخراج: `[{ \"name\": \"اسم الشركة\", \"address\": \"الشارع، الرمز البريدي، المدينة\", \"contact\": \"الهاتف أو البريد الإلكتروني\", \"website\": \"URL\" }]`",
    praktikumEmailPrompt: "أنت مساعد مهني ممتاز. اكتب مسودة بريد إلكتروني احترافية ومهذبة باللغة الألمانية. البريد الإلكتروني من '{userName}' إلى '{companyName}' للاستفسار عن تدريب عملي (Praktikum) في مجال '{field}'. الغرض من التدريب هو '{internshipType}'. قم بتكييف المحتوى والنبرة بشكل دقيق جدًا ليتناسب مع نوع التدريب:\n\n- إذا كان النوع 'للمدرسة' (Schülerpraktikum): اكتب كطالب متحمس. اذكر أن هذا تدريب مدرسي إلزامي. اسأل عن الفترة الزمنية الممكنة والمستندات المطلوبة. يجب أن تكون النبرة مهذبة وشبابية.\n- إذا كان النوع 'للتوجيه المهني' (Berufsorientierung): عبر عن اهتمام قوي بالمجال '{field}' وبالشركة. اشرح أن الهدف هو اكتساب رؤى أولية وتسهيل اختيار المهنة. يجب أن تكون النبرة فضولية ومتحمسة.\n- إذا كان النوع 'للأوسبيلدونج' (Ausbildung): اكتب بشكل أكثر رسمية واحترافية. اذكر أن المتقدم يسعى للحصول على تدريب مهني في هذا المجال ويرغب في اكتساب خبرة عملية. أكّد على الدافع لتطبيق المهارات عمليًا.\n\nاستخدم دائمًا تحية مناسبة (Sehr geehrte Damen und Herren,) وصيغة ختامية (Mit freundlichen Grüßen). اسأل عن الشخص المسؤول عن استلام طلبات التقديم.",
    internshipTypeLabel: "نوع التدريب العملي",
    internshipTypePlaceholder: "اختر نوع التدريب...",
    internshipTypeSchool: "للمدرسة",
    internshipTypeAusbildung: "للأوسبيلدونج",
    internshipTypeOrientation: "للتوجيه المهني",
    loading: "جاري التحميل...",
    underMaintenanceShort: "تحت الصيانة",
    underMaintenanceTitle: "هذا القسم تحت الصيانة",
    underMaintenanceDesc: "نحن نعمل حاليًا على تحسين هذا القسم وسيكون متاحًا قريبًا. يمكن للمسؤولين فقط الوصول إليه في الوقت الحالي.",
    systemInstruction: "أنت مستشار مهني خبير ومحلل نفسي متخصص في سوق العمل الألماني. مهمتك هي تحليل إجابات المستخدم {name}، البالغ من العمر {age} عامًا، على 30 سؤالًا لتقديم تقرير مهني مفصل وشخصي للغاية باللغة العربية. يجب أن يكون تحليلك عميقًا، ومشجعًا، وعمليًا. بناءً على الإجابات، قدم تقرير JSON مفصلًا يطابق المخطط. يجب أن يتضمن التقرير تحليلًا دقيقًا للشخصية، و3-4 اقتراحات وظيفية متنوعة جدًا ومناسبة (بما في ذلك Ausbildung والدراسة)، ونصائح مهنية قابلة للتنفيذ. خاطب المستخدم باسمه. يجب أن تكون لهجتك احترافية وداعمة للغاية.",
    promptIntro: "هذه هي بياناتي وإجاباتي على استبيان التوجيه المهني:",
    promptInstruction: "يرجى تقديم تحليلي المهني المفصل بناءً على هذه الإجابات.",
    schemaPersonality: "تحليل عميق ومفصل لشخصية المستخدم المهنية، نقاط القوة، مجالات التطوير، ونمط العمل المثالي، مكتوب بنبرة احترافية ومشجعة باللغة العربية.",
    schemaJobSuggestions: "قائمة من 3-4 اقتراحات مناسبة جدًا لوظائف أو تدريب مهني (Ausbildung) أو دراسة في ألمانيا باللغة العربية.",
    schemaTitle: "اسم الوظيفة أو التدريب المهني أو الدراسة باللغة العربية.",
    schemaDescription: "شرح مفصل ومقنع لماذا يناسب هذا المسار شخصية المستخدم وإجاباته، باللغة العربية.",
    schemaDetails: "تفاصيل رئيسية عملية مثل مدة التدريب، توقعات الراتب، متطلبات اللغة، أو فرص النمو في ألمانيا. باللغة العربية.",
    schemaCompanyName: "اسم الشركة.",
    schemaCompanyAddress: "العنوان الكامل للشركة.",
    schemaCompanyContact: "رقم هاتف الشركة أو البريد الإلكتروني.",
    schemaCompanyWebsite: "الموقع الإلكتروني الرسمي للشركة.",
    viewReports: "عرض التقارير",
    companyWebsite: "الموقع الإلكتروني",
    futureProjectTitle: "مشروع مستقبلي",
    futureProjectDesc: "هذه المساحة محجوزة لميزات جديدة ومثيرة.",
  },
  de: {
    langName: `${germanFlagImg} Deutsch`,
    dir: "ltr",
    headerTitle: "Berufsberatung mit Ahmad Mrashaha",
    footerText: "© 2025 - Entwickelt von Ahmad Mrashaha, um Ihnen zu helfen, Ihren Weg zu finden.",
    welcomeTitle: "Entdecken Sie Ihren idealen Karriereweg in Deutschland",
    welcomeDesc: "Beantworten Sie 30 präzise Fragen zu Ihrer Persönlichkeit, Ihren Fähigkeiten und Ambitionen. Unsere KI wird Ihre Antworten tiefgehend analysieren, um Ihnen die besten Karrierewege, Ausbildungen oder Studiengänge vorzuschlagen.",
    startQuiz: "Persönlichkeitstest starten",
    startQuizDesc: "Beantworten Sie unsere maßgeschneiderten Fragen und erhalten Sie eine persönliche Analyse Ihres Karrierewegs.",
    browseProfessions: "Berufe durchsuchen",
    browseProfessionsDesc: "Erkunden Sie unsere umfangreiche Datenbank mit Berufen, Ausbildungen und Studiengängen.",
    careerPathVideos: "Karrierevideos ansehen",
    careerPathVideosDesc: "Erfahren Sie mehr über verschiedene Berufe, indem Sie sich kurze Videos ansehen.",
    careerPathVideosTitle: "Karriereweg-Videos",
    careerPathVideosDescPage: "Durchsuchen Sie unsere Videosammlung, um einen Einblick in verschiedene Berufe aus dem wirklichen Leben zu erhalten.",
    searchAvailableJobs: "Verfügbare Stellen suchen",
    searchAvailableJobsDesc: "Finden Sie jetzt echte, verfügbare Stellenangebote in ganz Deutschland.",
    searchForPraktikum: "Praktikum suchen",
    searchForPraktikumDesc: "Finden Sie Praktikumsplätze und erstellen Sie professionelle Anfrage-E-Mails.",
    professionsDesc: "Suchen und durchsuchen Sie Hunderte von Stellenangeboten, Ausbildungen und Studiengängen in Deutschland.",
    back: "Zurück",
    next: "Weiter",
    getResults: "Meine Ergebnisse erhalten",
    loadingTitle: "Analysiere deine Persönlichkeit...",
    loadingDesc: "Unsere KI erstellt Ihren personalisierten Karrierebericht. Dies kann einen Moment dauern.",
    resultsTitleFor: "Ihr Karrierebericht für {name}",
    you: "Sie",
    personalitySummary: "Analyse Ihrer beruflichen Persönlichkeit",
    recommendedPaths: "Empfohlene Karrierewege",
    careerAdvice: "Personalisierte Karrieretipps",
    restart: "Zur Startseite",
    searchPlaceholder: "Suche nach einem Beruf...",
    all: "Alle",
    ausbildung: "Ausbildung",
    study: "Studium",
    job: "Job",
    duration: "Dauer",
    salary: "Gehalt",
    requirements: "Voraussetzungen",
    duties: "Aufgaben",
    home: "Startseite",
    errorText: "Entschuldigung, beim Erstellen Ihrer Ergebnisse ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
    answerHere: "Geben Sie Ihre Antwort hier ein...",
    page: "Seite",
    printReport: "Bericht drucken",
    emailReport: "Per E-Mail senden",
    saveReport: "Ergebnisse speichern",
    reportSaved: "Gespeichert!",
    emailSubject: "Mein Karrierebericht von Berufsberatung",
    jobSearchDesc: "Nutzen Sie KI, um nach aktuell verfügbaren Jobs oder Ausbildungsplätzen in Deutschland zu suchen. Geben Sie Berufsbezeichnung und Ort ein, um Live-Ergebnisse zu erhalten.",
    jobTitlePlaceholder: "z.B. Softwareentwickler, Pflegefachkraft...",
    locationPlaceholder: "z.B. Berlin, Hamburg...",
    search: "Suchen",
    jobSearchLoading: "Suche nach verfügbaren Stellen...",
    jobSearchSources: "Verfügbare Stellenangebote (Quellen)",
    jobSearchPrompt: "Finde mit Google Search aktuell verfügbare Stellenangebote oder Ausbildungsplätze für '{jobTitle}' in oder bei '{location}', Deutschland. Gib keine Zusammenfassung. Gib nur die originalen Quell-URLs an, die du gefunden hast.",
    noJobsFound: "Keine passenden Stellenangebote gefunden.",
    savedReportsTitle: "Gespeicherte Berichte",
    anonymousReport: "Anonymer Bericht",
    viewDetails: "Details ansehen",
    delete: "Löschen",
    confirmDeleteReport: "Möchten Sie diesen Bericht wirklich löschen?",
    noSavedReports: "Noch keine Berichte gespeichert.",
    adminLogin: "Admin-Login",
    responsibleLogin: "Verantwortlichen-Login",
    username: "Benutzername",
    password: "Passwort",
    login: "Anmelden",
    invalidCredentials: "Ungültiger Benutzername oder Passwort.",
    logout: "Abmelden",
    praktikumDesc: "Suchen Sie ein Praktikum? Geben Sie Ihren Interessenbereich und eine Stadt ein. Die KI findet passende Unternehmen für Sie. Wählen Sie eines aus und erstellen Sie dann einen professionellen E-Mail-Entwurf für Ihre Anfrage.",
    fieldPlaceholder: "z.B. IT, Marketing, Ingenieurwesen...",
    yourNamePlaceholder: "Ihr vollständiger Name",
    praktikumSearchBtn: "Unternehmen suchen",
    praktikumCompanyLoading: "Suche nach Praktikumsplatz...",
    praktikumCompanyResult: "Vorgeschlagene Unternehmen",
    company: "Unternehmen",
    location: "Standort",
    select: "Wählen",
    selected: "Ausgewählt",
    praktikumGenerateEmailTitle: "Anfrage-E-Mail erstellen",
    praktikumGenerateEmailBtn: "E-Mail erstellen",
    praktikumEmailLoading: "Schreibe deine E-Mail...",
    praktikumYourEmail: "Ihr E-Mail-Entwurf",
    copyEmail: "E-Mail kopieren",
    copied: "Kopiert!",
    praktikumSearchError: "Leider konnten wir keine passenden Unternehmen finden. Bitte versuchen Sie es mit anderen Suchbegriffen.",
    praktikumSearchPrompt: "ROLLE: Präzisions-Datenextraktor. \nHAUPTANWEISUNG: Nutze die Google-Suche, um Unternehmen für Praktika im Bereich '{field}' in '{location}', Deutschland zu finden. \nKRITISCHE REGEL 1: GENAUIGKEIT IST OBERSTES GEBOT. Es ist dir STRENGSTENS UNTERSAGT, Informationen zu erfinden, zu erraten oder abzuleiten. Deine einzige Quelle sind die bereitgestellten Google-Suchergebnisse. Wenn eine Information (wie eine Telefonnummer oder vollständige Adresse) in den Suchergebnissen nicht gefunden wird, MUSST du einen leeren String \"\" verwenden. \nKRITISCHE REGEL 2: Die GESAMTE Antwort MUSS ein sauberes, valides JSON-Array sein. Füge keinen erklärenden Text, keine Notizen oder Markdown wie ```json hinzu. Die Antwort muss mit [ beginnen und mit ] enden. \nAUSGABESCHEMA: `[{ \"name\": \"Firmenname\", \"address\": \"Straße, PLZ, Ort\", \"contact\": \"Telefon oder E-Mail\", \"website\": \"URL\" }]`",
    praktikumEmailPrompt: "Du bist ein exzellenter Karriere-Assistent. Schreibe einen professionellen und höflichen E-Mail-Entwurf auf Deutsch. Die E-Mail ist von '{userName}' an '{companyName}' gerichtet und fragt nach einem Praktikum im Bereich '{field}'. Der Zweck des Praktikums ist '{internshipType}'. Passe den Inhalt und Tonfall SEHR SPEZIFISCH an den Praktikumstyp an:\n\n- Wenn der Typ 'Für die Schule' ist: Schreibe als motivierter Schüler. Erwähne, dass es sich um ein obligatorisches Schulpraktikum handelt. Frage nach dem möglichen Zeitraum und den Bewerbungsunterlagen. Der Ton sollte höflich und jugendlich sein.\n- Wenn der Typ 'Zur Berufsorientierung' ist: Drücke starkes Interesse am Berufsfeld '{field}' und am Unternehmen aus. Erkläre, dass das Praktikum dazu dient, erste Einblicke zu gewinnen und die Berufswahl zu erleichtern. Der Ton sollte neugierig und engagiert sein.\n- Wenn der Typ 'Für die Ausbildung' ist: Schreibe formeller und professioneller. Gib an, dass der Bewerber eine Ausbildung in diesem Bereich anstrebt und praktische Erfahrung sammeln möchte. Betone die Motivation, die im Unternehmen erlernten Fähigkeiten in die Praxis umzusetzen.\n\nVerwende immer eine passende Anrede (Sehr geehrte Damen und Herren,) und Grußformel (Mit freundlichen Grüßen). Frage nach einem Ansprechpartner für die Bewerbung.",
    internshipTypeLabel: "Art des Praktikums",
    internshipTypePlaceholder: "Art des Praktikums wählen...",
    internshipTypeSchool: "Für die Schule",
    internshipTypeAusbildung: "Für die Ausbildung",
    internshipTypeOrientation: "Zur Berufsorientierung",
    loading: "Wird geladen...",
    underMaintenanceShort: "Wird gewartet",
    underMaintenanceTitle: "Dieser Bereich wird derzeit gewartet",
    underMaintenanceDesc: "Wir arbeiten derzeit an der Verbesserung dieses Bereichs. Er wird in Kürze verfügbar sein. Nur Administratoren können derzeit darauf zugreifen.",
    systemInstruction: "Sie sind ein erfahrener Karriereberater und Psychologe, spezialisiert auf den deutschen Arbeitsmarkt. Ihre Aufgabe ist es, die Antworten von {name}, {age} Jahre alt, auf 30 Fragen zu analysieren, um einen sehr detaillierten und persönlichen Karrierebericht auf Deutsch zu erstellen. Ihre Analyse muss tiefgründig, ermutigend und praktisch sein. Erstellen Sie basierend auf den Antworten einen detaillierten JSON-bericht, der dem Schema entspricht. Der Bericht muss eine genaue Persönlichkeitsanalyse, 3-4 sehr passende und vielfältige Jobvorschläge (einschließlich Ausbildung und Studium) und umsetzbare Karrieretipps enthalten. Sprechen Sie den Benutzer mit seinem Namen an. Ihr Ton muss professionell und sehr unterstützend sein.",
    promptIntro: "Hier sind meine Daten und Antworten auf den Karriere-Fragebogen:",
    promptInstruction: "Bitte erstellen Sie meine detaillierte Karriereanalyse basierend auf diesen Antworten.",
    schemaPersonality: "Eine tiefgehende und detaillierte Analyse der beruflichen Persönlichkeit, Stärken, Entwicklungsbereiche und des idealen Arbeitsstils des Benutzers, in einem professionellen und ermutigenden Ton auf Deutsch verfasst.",
    schemaJobSuggestions: "Eine Liste von 3-4 sehr passenden Vorschlägen für Jobs, Ausbildungen oder Studiengänge in Deutschland auf Deutsch.",
    schemaTitle: "Der Name des Jobs, der Ausbildung oder des Studiums auf Deutsch.",
    schemaDescription: "Eine detaillierte und überzeugende Erklärung, warum dieser Weg zur Persönlichkeit und den Antworten des Benutzers passt, auf Deutsch.",
    schemaDetails: "Wichtige, praktische Details wie Ausbildungsdauer, Gehaltsaussichten, Sprachanforderungen oder Wachstumschancen in Deutschland. Auf Deutsch.",
    schemaCompanyName: "Der Name des Unternehmens.",
    schemaCompanyAddress: "Die vollständige Adresse des Unternehmens.",
    schemaCompanyContact: "Telefonnummer oder E-Mail-Adresse des Unternehmens.",
    schemaCompanyWebsite: "Die offizielle Webseite des Unternehmens.",
    viewReports: "Berichte anzeigen",
    companyWebsite: "Webseite",
    futureProjectTitle: "Zukünftiges Projekt",
    futureProjectDesc: "Dieser Bereich ist für neue und aufregende Funktionen reserviert.",
  },
  tr: {
    langName: `${turkishFlagImg} Türkçe`,
    dir: "ltr",
    headerTitle: "Ahmad Mrashaha ile Kariyer Rehberliği",
    footerText: "© 2025 - Yolunuzu bulmanıza yardımcı olmak için Ahmad Mrashaha tarafından geliştirildi.",
    welcomeTitle: "Almanya'daki İdeal Kariyer Yolunuzu Keşfedin",
    welcomeDesc: "Kişiliğiniz, becerileriniz ve hedefleriniz hakkında 30 hassas soruyu yanıtlayın. Yapay zekamız, size en iyi kariyer yollarını, mesleki eğitimi (Ausbildung) veya üniversite programlarını önermek için cevaplarınızı derinlemesine analiz edecektir.",
    startQuiz: "Kişilik Testine Başla",
    startQuizDesc: "Size özel hazırlanmış sorularımızı yanıtlayın ve kariyer yolunuzun kişisel bir analizini alın.",
    browseProfessions: "Mesleklere Göz At",
    browseProfessionsDesc: "Geniş meslek, mesleki eğitim ve üniversite programları veritabanımızı keşfedin.",
    careerPathVideos: "Kariyer Videolarını İzle",
    careerPathVideosDesc: "Kısa videolar izleyerek farklı meslekler hakkında daha fazla bilgi edinin.",
    careerPathVideosTitle: "Kariyer Yolu Videoları",
    careerPathVideosDescPage: "Çeşitli mesleklere gerçek hayattan bir bakış atmak için video koleksiyonumuza göz atın.",
    searchAvailableJobs: "Mevcut İşleri Ara",
    searchAvailableJobsDesc: "Almanya genelinde şu anda mevcut olan gerçek iş fırsatlarını bulun.",
    searchForPraktikum: "Staj Ara (Praktikum)",
    searchForPraktikumDesc: "Staj yerleri bulun ve profesyonel başvuru e-postaları oluşturun.",
    professionsDesc: "Almanya'daki yüzlerce iş, mesleki eğitim ve üniversite fırsatını arayın ve inceleyin.",
    back: "Geri",
    next: "İleri",
    getResults: "Sonuçlarımı Al",
    loadingTitle: "Kişiliğiniz analiz ediliyor...",
    loadingDesc: "Yapay zeka kişiselleştirilmiş kariyer raporunuzu hazırlıyor. Bu birkaç dakika sürebilir.",
    resultsTitleFor: "{name} için Kariyer Raporun",
    you: "Sizin",
    personalitySummary: "Profesyonel Kişilik Analiziniz",
    recommendedPaths: "Önerilen Kariyer Yolları",
    careerAdvice: "Kişiselleştirilmiş Kariyer Tavsiyeleri",
    restart: "Ana Sayfaya Dön",
    searchPlaceholder: "Bir meslek arayın...",
    all: "Tümü",
    ausbildung: "Mesleki Eğitim",
    study: "Üniversite",
    job: "İş",
    duration: "Süre",
    salary: "Maaş",
    requirements: "Gereksinimler",
    duties: "Görevler",
    home: "Ana Sayfa",
    errorText: "Üzgünüz, sonuçlarınız oluşturulurken bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
    answerHere: "Cevabınızı buraya yazın...",
    page: "Sayfa",
    printReport: "Raporu Yazdır",
    emailReport: "E-posta ile Gönder",
    saveReport: "Sonuçları Kaydet",
    reportSaved: "Kaydedildi!",
    emailSubject: "Kariyer Rehberliği'nden Kariyer Raporum",
    jobSearchDesc: "Almanya'da mevcut işleri veya mesleki eğitim fırsatlarını aramak için yapay zekayı kullanın. Canlı sonuçlar almak için iş unvanını ve konumu girin.",
    jobTitlePlaceholder: "Örn: Yazılım Geliştirici, Hemşire...",
    locationPlaceholder: "Örn: Berlin, Hamburg...",
    search: "Ara",
    jobSearchLoading: "Mevcut işler aranıyor...",
    jobSearchSources: "Mevcut İş İlanları (Kaynaklar)",
    jobSearchPrompt: "Google Arama'yı kullanarak, Almanya'da '{location}' veya yakınında '{jobTitle}' için mevcut iş veya mesleki eğitim (Ausbildung) ilanlarını bulun. Bir özet sunmayın. Sadece bulduğunuz orijinal kaynak URL'lerini sağlayın.",
    noJobsFound: "Uygun iş ilanı bulunamadı.",
    savedReportsTitle: "Kayıtlı Raporlar",
    anonymousReport: "İsimsiz Rapor",
    viewDetails: "Detayları Görüntüle",
    delete: "Sil",
    confirmDeleteReport: "Bu raporu silmek istediğinizden emin misiniz?",
    noSavedReports: "Henüz kayıtlı rapor yok.",
    adminLogin: "Yönetici Girişi",
    responsibleLogin: "Sorumlu Girişi",
    username: "Kullanıcı Adı",
    password: "Şifre",
    login: "Giriş Yap",
    invalidCredentials: "Geçersiz kullanıcı adı veya şifre.",
    logout: "Çıkış Yap",
    praktikumDesc: "Staj mı arıyorsunuz? İlgilendiğiniz alanı ve bir şehri girin. Yapay zeka sizin için uygun şirketleri bulacaktır. Birini seçin ve ardından profesyonel bir başvuru e-postası taslağı oluşturun.",
    fieldPlaceholder: "Örn: Bilişim, Pazarlama, Mühendislik...",
    yourNamePlaceholder: "Tam adınız",
    praktikumSearchBtn: "Şirketleri Ara",
    praktikumCompanyLoading: "Staj fırsatları aranıyor...",
    praktikumCompanyResult: "Önerilen Şirketler",
    company: "Şirket",
    location: "Konum",
    select: "Seç",
    selected: "Seçildi",
    praktikumGenerateEmailTitle: "Soru E-postası Oluştur",
    praktikumGenerateEmailBtn: "E-posta Oluştur",
    praktikumEmailLoading: "E-postanız yazılıyor...",
    praktikumYourEmail: "E-posta Taslağınız",
    copyEmail: "E-postayı Kopyala",
    copied: "Kopyalandı!",
    praktikumSearchError: "Maalesef uygun bir şirket bulamadık. Lütfen farklı arama terimleriyle tekrar deneyin.",
    praktikumSearchPrompt: "ROL: Hassas veri çıkarıcı. \nANA YÖNERGE: '{location}', Almanya'da '{field}' alanında staj için şirketleri bulmak üzere Google Arama'yı kullan. \nKRİTİK KURAL 1: DOĞRULUK ESASTIR. Herhangi bir bilgiyi uydurmak, tahmin etmek veya çıkarmak KESİNLİKLE YASAKTIR. Tek kaynağın sağlanan Google Arama sonuçlarıdır. Arama sonuçlarında bir bilgi (telefon numarası veya tam adres gibi) bulunamazsa, boş bir dize \"\" kullanmak ZORUNLUDUR. \nKRİTİK KURAL 2: Yanıtın TAMAMI temiz, geçerli bir JSON dizisi OLMALIDIR. ```json gibi açıklayıcı metin, not veya markdown ekleme. Yanıt [ ile başlamalı ve ] ile bitmelidir. \nÇIKTI ŞEMASI: `[{ \"name\": \"Şirket Adı\", \"address\": \"Cadde, Posta Kodu, Şehir\", \"contact\": \"Telefon veya E-posta\", \"website\": \"URL\" }]`",
    praktikumEmailPrompt: "Sen mükemmel bir kariyer asistanısın. Almanca olarak profesyonel ve nazik bir e-posta taslağı yaz. E-posta, '{userName}' adından '{companyName}' şirketine '{field}' alanında bir staj (Praktikum) hakkında bilgi almak için yazılmıştır. Stajın amacı: '{internshipType}'. İçeriği ve tonu staj türüne göre ÇOK ÖZGÜN bir şekilde uyarla:\n\n- Eğer tür 'Okul için' ise: Motive bir öğrenci olarak yaz. Bunun zorunlu bir okul stajı olduğunu belirt. Mümkün olan zaman aralığını ve başvuru belgelerini sor. Ton kibar ve genç olmalıdır.\n- Eğer tür 'Kariyer Yönelimi için' ise: '{field}' alanına ve şirkete olan güçlü ilgini ifade et. Stajın amacının ilk izlenimleri kazanmak ve kariyer seçimini kolaylaştırmak olduğunu açıkla. Ton meraklı ve hevesli olmalıdır.\n- Eğer tür 'Mesleki Eğitim için' ise: Daha resmi ve profesyonel yaz. Başvuranın bu alanda bir mesleki eğitim hedeflediğini ve pratik deneyim kazanmak istediğini belirt. Şirkette öğrenilen becerileri pratiğe dökme motivasyonunu vurgula.\n\nHer zaman uygun bir hitap (Sehr geehrte Damen und Herren,) ve kapanış ifadesi (Mit freundlichen Grüßen) kullan. Başvuru için bir yetkili kişi olup olmadığını sor.",
    internshipTypeLabel: "Staj Türü",
    internshipTypePlaceholder: "Staj türünü seçin...",
    internshipTypeSchool: "Okul için",
    internshipTypeAusbildung: "Mesleki Eğitim için",
    internshipTypeOrientation: "Kariyer Yönelimi için",
    loading: "Yükleniyor...",
    underMaintenanceShort: "Bakımda",
    underMaintenanceTitle: "Bu Bölüm Bakımda",
    underMaintenanceDesc: "Şu anda bu bölümü geliştirmek için çalışıyoruz ve yakında kullanıma sunulacaktır. Şu anda yalnızca yöneticiler erişebilir.",
    systemInstruction: "Alman iş piyasasında uzmanlaşmış deneyimli bir kariyer danışmanı ve psikologsunuz. Göreviniz, {name} adlı, {age} yaşındaki kullanıcının 30 soruya verdiği yanıtları analiz ederek Türkçe olarak çok ayrıntılı ve kişisel bir kariyer raporu sunmaktır. Analiziniz derinlemesine, teşvik edici ve pratik olmalıdır. Yanıtlara dayanarak, şemaya uygun ayrıntılı bir JSON raporu oluşturun. Rapor, doğru bir kişilik analizi, 3-4 çok uygun ve çeşitli iş önerisi (Ausbildung ve üniversite dahil) ve uygulanabilir kariyer tavsiyeleri içermelidir. Kullanıcıya adıyla hitap edin. Tonunuz profesyonel ve çok destekleyici olmalıdır.",
    promptIntro: "İşte benim verilerim ve kariyer rehberliği anketine verdiğim yanıtlar:",
    promptInstruction: "Lütfen bu yanıtlara dayanarak ayrıntılı kariyer analizimi yapın.",
    schemaPersonality: "Kullanıcının profesyonel kişiliğinin, güçlü yönlerinin, gelişim alanlarının ve ideal çalışma tarzının, profesyonel ve teşvik edici bir tonda Türkçe yazılmış derinlemesine ve ayrıntılı bir analizi.",
    schemaJobSuggestions: "Almanya'da 3-4 çok uygun iş, mesleki eğitim (Ausbildung) veya üniversite programı önerisinden oluşan bir liste (Türkçe).",
    schemaTitle: "İşin, mesleki eğitimin veya üniversite programının adı (Türkçe).",
    schemaDescription: "Bu yolun neden kullanıcının kişiliğine ve yanıtlarına uygun olduğuna dair ayrıntılı ve ikna edici bir açıklama (Türkçe).",
    schemaDetails: "Almanya'daki eğitim süresi, maaş beklentileri, dil gereksinimleri veya büyüme fırsatları gibi önemli, pratik ayrıntılar (Türkçe).",
    schemaCompanyName: "Şirketin adı.",
    schemaCompanyAddress: "Şirketin tam adresi.",
    schemaCompanyContact: "Şirketin telefon numarası veya e-posta adresi.",
    schemaCompanyWebsite: "Şirketin resmi web sitesi.",
    viewReports: "Raporları Görüntüle",
    companyWebsite: "İnternet sitesi",
    futureProjectTitle: "Gelecek Proje",
    futureProjectDesc: "Bu alan yeni ve heyecan verici özellikler için ayrılmıştır.",
  },
  uk: {
    langName: `${ukrainianFlagImg} Українська`,
    dir: "ltr",
    headerTitle: "Кар'єрне консультування з Ahmad Mrashaha",
    footerText: "© 2025 - Розроблено Ahmad Mrashaha, щоб допомогти вам знайти свій шлях.",
    welcomeTitle: "Знайдіть свій ідеальний кар'єрний шлях у Німеччині",
    welcomeDesc: "Дайте відповідь на 30 точних запитань про вашу особистість, навички та амбіції. Наш ШІ глибоко проаналізує ваші відповіді, щоб запропонувати найкращі кар'єрні шляхи, професійне навчання (Ausbildung) або університетські програми.",
    startQuiz: "Почати тест особистості",
    startQuizDesc: "Дайте відповідь на наші спеціально розроблені запитання та отримайте особистий аналіз вашого кар'єрного шляху.",
    browseProfessions: "Переглянути професії",
    browseProfessionsDesc: "Досліджуйте нашу велику базу даних професій, програм професійного навчання та університетських курсів.",
    careerPathVideos: "Переглянути кар'єрні відео",
    careerPathVideosDesc: "Дізнайтеся більше про різні професії, переглядаючи короткі відео.",
    careerPathVideosTitle: "Відео про кар'єрні шляхи",
    careerPathVideosDescPage: "Перегляньте нашу колекцію відео, щоб отримати реалістичне уявлення про різні професії.",
    searchAvailableJobs: "Шукати доступні вакансії",
    searchAvailableJobsDesc: "Знайдіть реальні, доступні вакансії по всій Німеччині прямо зараз.",
    searchForPraktikum: "Шукати практику (Praktikum)",
    searchForPraktikumDesc: "Знаходьте місця для практики та створюйте професійні електронні листи для запитів.",
    professionsDesc: "Шукайте та переглядайте сотні вакансій, програм професійного навчання та університетських курсів у Німеччичині.",
    back: "Назад",
    next: "Далі",
    getResults: "Отримати мої результати",
    loadingTitle: "Аналізуємо вашу особистість...",
    loadingDesc: "Наш ШІ готує ваш персоналізований кар'єрний звіт. Це може зайняти кілька хвилин.",
    resultsTitleFor: "Ваш кар'єрний звіт для {name}",
    you: "Вас",
    personalitySummary: "Аналіз вашої професійної особистості",
    recommendedPaths: "Рекомендовані кар'єрні шляхи",
    careerAdvice: "Персоналізовані кар'єрні поради",
    restart: "На головну",
    searchPlaceholder: "Пошук професії...",
    all: "Всі",
    ausbildung: "Проф. навчання",
    study: "Навчання",
    job: "Робота",
    duration: "Тривалість",
    salary: "Зарплата",
    requirements: "Вимоги",
    duties: "Обов'язки",
    home: "Головна",
    errorText: "На жаль, сталася помилка під час створення ваших результатів. Будь ласка, спробуйте пізніше.",
    answerHere: "Введіть свою відповідь тут...",
    page: "Сторінка",
    printReport: "Роздрукувати звіт",
    emailReport: "Надіслати на Email",
    saveReport: "Зберегти результати",
    reportSaved: "Збережено!",
    emailSubject: "Мій кар'єрний звіт з Кар'єрного консультування",
    jobSearchDesc: "Використовуйте ШІ для пошуку актуальних вакансій або місць для професійного навчання в Німеччині. Введіть назву посади та місцезнаходження, щоб отримати результати в реальному часі.",
    jobTitlePlaceholder: "напр., розробник програмного забезпечення, медсестра...",
    locationPlaceholder: "напр., Берлін, Гамбург...",
    search: "Пошук",
    jobSearchLoading: "Шукаємо доступні вакансії...",
    jobSearchSources: "Доступні вакансії (Джерела)",
    jobSearchPrompt: "За допомогою Пошуку Google знайди актуальні вакансії або місця для професійного навчання (Ausbildung) за запитом '{jobTitle}' у місті '{location}' або його околицях, Німеччина. Не надавай резюме. Надай лише посилання на оригінальні джерела, які ти знайшов.",
    noJobsFound: "Відповідних вакансій не знайдено.",
    savedReportsTitle: "Збережені звіти",
    anonymousReport: "Анонімний звіт",
    viewDetails: "Переглянути деталі",
    delete: "Видалити",
    confirmDeleteReport: "Ви впевнені, що хочете видалити цей звіт?",
    noSavedReports: "Ще немає збережених звітів.",
    adminLogin: "Вхід для адміністратора",
    responsibleLogin: "Вхід для відповідального",
    username: "Ім'я користувача",
    password: "Пароль",
    login: "Увійти",
    invalidCredentials: "Неправильне ім'я користувача або пароль.",
    logout: "Вийти",
    praktikumDesc: "Шукаєте практику (Praktikum)? Введіть сферу інтересів та місто. ШІ знайде для вас відповідні компанії. Оберіть одну, а потім створіть професійний чернетковий лист-запит.",
    fieldPlaceholder: "напр., ІТ, маркетинг, інженерія...",
    yourNamePlaceholder: "Ваше повне ім'я",
    praktikumSearchBtn: "Шукати компанії",
    praktikumCompanyLoading: "Пошук місця практики...",
    praktikumCompanyResult: "Запропоновані компанії",
    company: "Компанія",
    location: "Місцезнаходження",
    select: "Обрати",
    selected: "Обрано",
    praktikumGenerateEmailTitle: "Створити лист-запит",
    praktikumGenerateEmailBtn: "Створити лист",
    praktikumEmailLoading: "Пишемо ваш лист...",
    praktikumYourEmail: "Ваш чернетковий лист",
    copyEmail: "Копіювати лист",
    copied: "Скопійовано!",
    praktikumSearchError: "На жаль, ми не змогли знайти відповідну компанію. Будь ласка, спробуйте інші пошукові терміни.",
    praktikumSearchPrompt: "РОЛЬ: Точний екстрактор даних. \nОСНОВНА ДИРЕКТИВА: Використовуй Пошук Google, щоб знайти компанії для стажування у сфері '{field}' у '{location}', Німеччина. \nКРИТИЧНЕ ПРАВИЛО 1: ТОЧНІСТЬ — НАЙГОЛОВНІШЕ. Вам СУВОРО ЗАБОРОНЕНО вигадувати, вгадувати або робити висновки щодо будь-якої інформації. Ваше єдине джерело — надані результати Пошуку Google. Якщо інформація (наприклад, номер телефону або повна адреса) не знайдена в результатах пошуку, ви ПОВИННІ використовувати порожній рядок \"\". \nКРИТИЧНЕ ПРАВИЛО 2: УСЯ відповідь ПОВИННА бути чистим, валідним масивом JSON. Не додавайте жодного пояснювального тексту, приміток або markdown, наприклад ```json. Відповідь має починатися з [ і закінчуватися ]. \nСХЕМА ВИВОДУ: `[{ \"name\": \"Назва компанії\", \"address\": \"Вулиця, Поштовий індекс, Місто\", \"contact\": \"Телефон або Email\", \"website\": \"URL\" }]`",
    praktikumEmailPrompt: "Ти — відмінний кар'єрний асистент. Напиши професійний та ввічливий чернетковий лист німецькою мовою. Лист від '{userName}' до '{companyName}' із запитом про практику (Praktikum) у сфері '{field}'. Мета практики: '{internshipType}'. Адаптуй зміст і тон ДУЖЕ КОНКРЕТНО до типу практики:\n\n- Якщо тип 'Для школи': Пиши як вмотивований учень. Згадай, що це обов'язкова шкільна практика. Запитай про можливі дати та необхідні документи. Тон має бути ввічливим і молодіжним.\n- Якщо тип 'Для профорієнтації': Вислови сильну зацікавленість у сфері '{field}' та в компанії. Поясни, що мета — отримати перші враження та полегшити вибір професії. Тон має бути допитливим та зацікавленим.\n- Якщо тип 'Для професійного навчання': Пиши більш формально та професійно. Вкажи, що заявник прагне отримати професійне навчання та хоче набути практичного досходу. Підкресли мотивацію застосувати навички на практиці.\n\nЗавжди використовуй відповідне звертання (Sehr geehrte Damen und Herren,) та заключну формулу (Mit freundlichen Grüßen). Запитай про контактну особу для подання заявки.",
    internshipTypeLabel: "Тип практики",
    internshipTypePlaceholder: "Оберіть тип практики...",
    internshipTypeSchool: "Для школи",
    internshipTypeAusbildung: "Для професійного навчання",
    internshipTypeOrientation: "Для профорієнтації",
    loading: "Завантаження...",
    underMaintenanceShort: "На обслуговуванні",
    underMaintenanceTitle: "Цей розділ на обслуговуванні",
    underMaintenanceDesc: "Наразі ми працюємо над покращенням цього розділу, і він незабаром буде доступний. На даний момент доступ мають лише адміністратори.",
    systemInstruction: "Ви - досвідчений кар'єрний консультант і психолог, що спеціалізується на німецькому ринку праці. Ваше завдання - проаналізувати відповіді користувача {name}, віком {age} років, на 30 запитань, щоб надати дуже детальний та особистий кар'єрний звіт українською мовою. Ваш аналіз має бути глибоким, підбадьорливим і практичним. На основі відповідей створіть детальний JSON-звіт, що відповідає схемі. Звіт повинен містити точний аналіз особистості, 3-4 дуже релевантні та різноманітні пропозиції роботи (включаючи Ausbildung та навчання) та дієві кар'єрні поради. Звертайтеся до користувача на ім'я. Ваш тон має бути професійним і дуже підтримуючим.",
    promptIntro: "Ось мої дані та відповіді на анкету з профорієнтації:",
    promptInstruction: "Будь ласка, надайте мій детальний кар'єрний аналіз на основі цих відповідей.",
    schemaPersonality: "Глибокий і детальний аналіз професійної особистості користувача, сильних сторін, зон для розвитку та ідеального стилю роботи, написаний професійним та підбадьорливим тоном українською мовою.",
    schemaJobSuggestions: "Список з 3-4 дуже релевантних пропозицій роботи, професійного навчання (Ausbildung) або навчання в Німеччині українською мовою.",
    schemaTitle: "Назва роботи, професійного навчання або курсу навчання українською мовою.",
    schemaDescription: "Детальне і переконливе пояснення, чому цей шлях відповідає особистості та відповідям користувача, українською мовою.",
    schemaDetails: "Ключові практичні деталі, такі як тривалість навчання, очікувана зарплата, мовні вимоги або перспективи зростання в Німеччині. Українською мовою.",
    schemaCompanyName: "Назва компанії.",
    schemaCompanyAddress: "Повна адреса компанії.",
    schemaCompanyContact: "Номер телефону або електронна адреса компанії.",
    schemaCompanyWebsite: "Офіційний веб-сайт компанії.",
    viewReports: "Переглянути звіти",
    companyWebsite: "Веб-сайт",
    futureProjectTitle: "Майбутній проект",
    futureProjectDesc: "Це місце зарезервовано для нових захоплюючих функцій.",
  }
};

export const quizQuestions = {
  ar: [
    { type: 'text', id: 'name', question: "لنبدأ، ما هو اسمك الأول؟" },
    { type: 'number', id: 'age', question: "كم عمرك؟" },
    { question: "أي بيئة عمل تفضل؟", options: ["مكتب هادئ ومنظم", "بيئة ديناميكية ومتغيرة", "في الهواء الطلق أو أثناء التنقل", "ورشة عمل أو معمل"] },
    { question: "ما نوع المهام التي تستمتع بها أكثر؟", options: ["حل المشكلات المعقدة والتحليل", "الإبداع وتصميم أشياء جديدة", "مساعدة الناس ودعمهم", "التنظيم والتخطيط الدقيق"] },
    { question: "كيف تصف أسلوب عملك؟", options: ["أعمل بشكل أفضل بمفردي", "أستمتع بالعمل ضمن فريق", "أحب قيادة الفرق والمشاريع", "أتكيف مع أي أسلوب مطلوب"] },
    { question: "ما مدى أهمية الراتب المرتفع بالنسبة لك؟", options: ["مهم جداً، هو أولويتي", "مهم، لكن ليس أهم شيء", "متوسط الأهمية", "أفضل وظيفة أحبها براتب أقل"] },
    { question: "ما هو دافعك الأساسي في العمل؟", options: ["الإنجاز وتحقيق الأهداف", "تعلم مهارات جديدة باستمرار", "إحداث تأثير إيجابي في المجتمع", "الاستقرار والأمان الوظيفي"] },
    { question: "كيف تتعامل مع الضغط والمواعيد النهائية؟", options: ["أزدهر تحت الضغط", "أديره بشكل جيد ومنظم", "أشعر ببعض التوتر لكن أنجز العمل", "أفضل بيئة عمل خالية من الضغط"] },
    { question: "تواجه مشكلة تقنية معقدة في العمل لم يسبق لك التعامل معها. ما هي خطوتك الأولى؟", options: ["أبحث عن حلول عبر الإنترنت وأقرأ الوثائق الفنية بمفردي.", "أطلب المساعدة فوراً من زميل أكثر خبرة أو من مديري.", "أقوم بتجربة حلول مختلفة مباشرةً لأرى ما ينجح (التجربة والخطأ).", "أقوم بتقسيم المشكلة إلى أجزاء أصغر وأحلل كل جزء على حدة قبل البدء."] },
    { question: "ما هو مستواك الحالي في اللغة الألمانية؟", options: ["لا أجيدها (A0)", "مبتدئ (A1/A2)", "متوسط (B1/B2)", "متقدم (C1/C2)", "لغة أم"] },
    { question: "ما هو أعلى مؤهل دراسي حصلت عليه؟", options: ["أقل من الثانوية", "شهادة ثانوية", "دبلوم أو تدريب مهني", "شهادة جامعية أو أعلى"] },
    { question: "هل تفضل العمل مع البيانات والأرقام أم مع الأفكار والمفاهيم؟", options: ["البيانات والأرقام", "الأفكار والمفاهيم", "مزيج من الاثنين", "لا أفضل أياً منهما"] },
    { question: "ما مدى أهمية الإبداع في وظيفتك؟", options: ["أساسي ومحوري", "مهم ومطلوب أحياناً", "إضافة جيدة ولكنه ليس ضرورياً", "غير مهم على الإطلاق"] },
    { question: "كيف تتعامل مع المهام الروتينية والمتكررة؟", options: ["أستمتع بها، فهي مريحة", "أتحملها كجزء من العمل", "أجدها مملة للغاية", "أحاول أتمتتها أو تفويضها"] },
    { question: "عندما تحتاج إلى إيصال فكرة مهمة ومعقدة لفريقك، أي طريقة تفضل؟", options: ["كتابة بريد إلكتروني مفصل أو وثيقة شاملة.", "عقد اجتماع وتقديم عرض تقديمي مرئي.", "مناقشة الفكرة بشكل فردي مع كل عضو في الفريق.", "استخدام لوح أبيض أو أداة مرئية لشرحها بشكل تفاعلي."] },
    { question: "ما هو الدور الذي تلعبه عادة في مجموعة؟", options: ["القائد", "المحلل والمخطط", "صانع السلام ومنسق الفريق", "المنفذ العملي"] },
    { question: "أي من هذه المهارات تصفك بشكل أفضل؟", options: ["التفكير النقدي", "التواصل الفعال", "البراعة اليدوية", "التعاطف وفهم الآخرين"] },
    { question: "أمامك فرصة لتطوير مهاراتك. أي خيار تختار؟", options: ["دورة تدريبية متقدمة للحصول على شهادة معتمدة في مجالي الحالي.", "مشروع جديد يتحدى قدراتي ويتطلب مني تعلم مهارات مختلفة تمامًا.", "حضور مؤتمرات وورش عمل للتواصل مع الخبراء.", "تولي دور إرشادي لتعليم المبتدئين."] },
    { question: "هل تفضل وظيفة ذات مسار وظيفي واضح أم وظيفة تسمح لك بتشكيل دورك الخاص؟", options: ["مسار وظيفي واضح", "تشكيل دوري الخاص", "لا يوجد تفضيل قوي", "لست متأكداً"] },
    { question: "ما مدى أهمية العمل البدني في وظيفتك؟", options: ["أفضل وظيفة نشطة بدنياً", "لا أمانع بعض النشاط البدني", "أفضل وظيفة مكتبية بشكل أساسي", "يجب أن تكون وظيفة مكتبية تماماً"] },
    { question: "كيف تتعامل مع النقد البناء؟", options: ["أقدره وأبحث عنه بنشاط", "أتقبله وأتعلم منه", "أشعر ببعض الدفاعية في البداية", "أجده صعباً ومثبطاً للعزيمة"] },
    { question: "هل أنت شخص يركز على الصورة الكبيرة أم على التفاصيل الدقيقة؟", options: ["الصورة الكبيرة والاستراتيجية", "التفاصيل الدقيقة والتنفيذ", "أستطيع التبديل بينهما بسهولة", "لست متأكداً"] },
    { question: "قررت الشركة فجأة تغيير استراتيجيتها الرئيسية، مما يؤثر بشكل مباشر على مشروعك. كيف تتصرف؟", options: ["أشعر بالإحباط بسبب الجهد الضائع، ولكنني أتكيف مع الاتجاه الجديد.", "أبحث فوراً عن فهم الأسباب وراء التغيير وكيف يمكن لمشروعي أن يتناسب مع الاستراتيجية الجديدة.", "أركز على إنهاء المهام المتبقية من المشروع القديم قبل التفكير في أي شيء جديد.", "أرى في ذلك فرصة لاقتراح أفكار جديدة تتماشى مع الاستراتيجية الجديدة."] },
    { question: "هل تفضل بيئة عمل رسمية أم غير رسمية؟", options: ["رسمية ومنظمة", "غير رسمية ومريحة", "مزيج إبداعي", "لا يهم"] },
    { question: "ما مدى أهمية مساعدة الآخرين أو المجتمع من خلال عملك؟", options: ["مهم للغاية", "مهم إلى حد ما", "إضافة لطيفة", "ليس من أولوياتي"] },
    { question: "ما هو أسلوبك في اتخاذ القرارات؟", options: ["تحليلي قائم على البيانات", "حدسي قائم على الشعور", "تعاوني بعد التشاور مع الآخرين", "سريع وحاسم"] },
    { question: "أي من هذه العوامل هو الأكثر أهمية لك في بيئة العمل المثالية؟", options: ["الاستقلالية والحرية في كيفية إنجاز عملي.", "فريق عمل داعم ومتعاون وبيئة اجتماعية إيجابية.", "فرص واضحة للترقية والنمو الوظيفي داخل الشركة.", "العمل على منتجات أو خدمات مبتكرة ورائدة في السوق."] },
    { question: "ما الذي تأمل في تحقيقه في السنوات الخمس القادمة؟", options: ["الاستقرار المالي والمنزل", "الخبرة والنمو المهني السريع", "إتقان حرفة أو مهارة معينة", "إطلاق مشروعي الخاص"] },
    { type: 'text', question: "صف موقفاً احتجت فيه إلى تعلم مهارة تقنية جديدة بسرعة لإكمال مشروع. ما هي الخطوات التي اتخذتها، وماذا كانت النتيجة؟" },
    { type: 'text', question: "بالنظر إلى أهدافك المهنية، كيف تتخيل أن تتكامل حياتك المهنية مع حياتك الشخصية بعد 5 سنوات من الآن؟ ما هو نوع المرونة الذي تحتاجه لتحقيق ذلك؟" },
  ],
  de: [
    { type: 'text', id: 'name', question: "Fangen wir an, wie lautet Ihr Vorname?" },
    { type: 'number', id: 'age', question: "Wie alt sind Sie?" },
    { question: "Welche Arbeitsumgebung bevorzugen Sie?", options: ["Ruhiges, organisiertes Büro", "Dynamisches, sich veränderndes Umfeld", "Im Freien oder unterwegs", "Werkstatt oder Labor"] },
    { question: "Welche Art von Aufgaben macht Ihnen am meisten Spaß?", options: ["Komplexe Probleme lösen & analysieren", "Kreativ sein & Neues gestalten", "Menschen helfen & unterstützen", "Präzises Organisieren & Planen"] },
    { question: "Wie beschreiben Sie Ihren Arbeitsstil?", options: ["Ich arbeite am besten allein", "Ich genieße die Arbeit im Team", "Ich liebe es, Teams und Projekte zu leiten", "Ich passe mich jedem Stil an"] },
    { question: "Wie wichtig ist Ihnen ein hohes Gehalt?", options: ["Sehr wichtig, meine Priorität", "Wichtig, aber nicht alles", "Mäßig wichtig", "Ich bevorzuge einen Job, den ich liebe, mit weniger Gehalt"] },
    { question: "Was ist Ihre primäre Motivation bei der Arbeit?", options: ["Leistung & Ziele erreichen", "Ständig neue Fähigkeiten lernen", "Einen positiven Einfluss auf die Gesellschaft haben", "Stabilität & Arbeitsplatzsicherheit"] },
    { question: "Wie gehen Sie mit Druck und Fristen um?", options: ["Ich blühe unter Druck auf", "Ich manage es gut und organisiert", "Ich werde etwas gestresst, aber erledige die Arbeit", "Ich bevorzuge eine stressfreie Umgebung"] },
    { question: "Sie stoßen bei der Arbeit auf ein komplexes technisches Problem, mit dem Sie noch nie konfrontiert waren. Was ist Ihr erster Schritt?", options: ["Ich suche online nach Lösungen und lese die technische Dokumentation selbst.", "Ich bitte sofort einen erfahreneren Kollegen oder meinen Vorgesetzten um Hilfe.", "Ich probiere verschiedene Lösungen direkt aus, um zu sehen, was funktioniert (Versuch und Irrtum).", "Ich zerlege das Problem in kleinere Teile und analysiere jeden Teil, bevor ich beginne."] },
    { question: "Was ist Ihr aktuelles deutsches Sprachniveau?", options: ["Keine Kenntnisse (A0)", "Anfänger (A1/A2)", "Mittelstufe (B1/B2)", "Fortgeschritten (C1/C2)", "Muttersprache"] },
    { question: "Was ist Ihr höchster Bildungsabschluss?", options: ["Weniger als Abitur", "Abitur/Fachabitur", "Diplom oder Berufsausbildung", "Universitätsabschluss oder höher"] },
    { question: "Arbeiten Sie lieber mit Daten & Zahlen oder mit Ideen & Konzepten?", options: ["Daten & Zahlen", "Ideen & Konzepte", "Eine Mischung aus beidem", "Keines von beiden"] },
    { question: "Wie wichtig ist Kreativität in Ihrem Job?", options: ["Unerlässlich und zentral", "Wichtig und manchmal erforderlich", "Ein nettes Extra, aber nicht notwendig", "Überhaupt nicht wichtig"] },
    { question: "Wie gehen Sie mit Routineaufgaben um?", options: ["Ich genieße sie, sie sind beruhigend", "Ich toleriere sie als Teil des Jobs", "Ich finde sie extrem langweilig", "Ich versuche, sie zu automatisieren oder zu delegieren"] },
    { question: "Wenn Sie Ihrem Team eine wichtige, komplexe Idee mitteilen müssen, welche Methode bevorzugen Sie?", options: ["Eine detaillierte E-Mail oder ein umfassendes Dokument schreiben.", "Ein Meeting abhalten und eine visuelle Präsentation geben.", "Die Idee einzeln mit jedem Teammitglied besprechen.", "Ein Whiteboard oder ein visuelles Tool verwenden, um es interaktiv zu erklären."] },
    { question: "Welche Rolle nehmen Sie normalerweise in einer Gruppe ein?", options: ["Der Anführer", "Der Analytiker & Planer", "Der Friedensstifter & Team-Koordinator", "Der praktische Macher"] },
    { question: "Welche dieser Fähigkeiten beschreibt Sie am besten?", options: ["Kritisches Denken", "Effektive Kommunikation", "Handwerkliches Geschick", "Empathie & Verständnis für andere"] },
    { question: "Sie haben die Möglichkeit, Ihre Fähigkeiten weiterzuentwickeln. Welche Option wählen Sie?", options: ["Ein Fortgeschrittenenkurs, um eine anerkannte Zertifizierung in meinem aktuellen Bereich zu erhalten.", "Ein neues Projekt, das meine Fähigkeiten herausfordert und von mir verlangt, völlig andere Fähigkeiten zu erlernen.", "Teilnahme an Konferenzen und Workshops, um mich mit Experten zu vernetzen.", "Eine Mentorenrolle übernehmen, um Anfänger zu unterrichten."] },
    { question: "Bevorzugen Sie einen klaren Karriereweg oder einen Job, bei dem Sie Ihre Rolle selbst gestalten können?", options: ["Klarer Karriereweg", "Meine eigene Rolle gestalten", "Keine starke Präferenz", "Ich bin mir nicht sicher"] },
    { question: "Wie wichtig ist körperliche Arbeit in Ihrem Job?", options: ["Ich bevorzuge einen körperlich aktiven Job", "Etwas körperliche Aktivität ist in Ordnung", "Ich bevorzuge hauptsächlich einen Bürojob", "Es muss ein reiner Bürojob sein"] },
    { question: "Wie gehen Sie mit konstruktiver Kritik um?", options: ["Ich schätze sie und suche aktiv danach", "Ich akzeptiere sie und lerne daraus", "Ich reagiere anfangs etwas defensiv", "Ich finde sie schwierig und demotivierend"] },
    { question: "Sind Sie eine Person, die sich auf das große Ganze oder auf die feinen Details konzentriert?", options: ["Das große Ganze & Strategie", "Die feinen Details & Ausführung", "Ich kann leicht zwischen beidem wechseln", "Ich bin mir nicht sicher"] },
    { question: "Das Unternehmen beschließt plötzlich, seine Hauptstrategie zu ändern, was sich direkt auf Ihr Projekt auswirkt. Wie reagieren Sie?", options: ["Ich bin frustriert über die verschwendete Mühe, passe mich aber der neuen Richtung an.", "Ich versuche sofort, die Gründe für die Änderung zu verstehen und wie mein Projekt zur neuen Strategie passen kann.", "Ich konzentriere mich darauf, die verbleibenden Aufgaben des alten Projekts abzuschließen, bevor ich über etwas Neues nachdenke.", "Ich sehe es als eine Gelegenheit, neue Ideen vorzuschlagen, die zur neuen Strategie passen."] },
    { question: "Bevorzugen Sie eine formelle oder eine informelle Arbeitsumgebung?", options: ["Formell und strukturiert", "Informell und entspannt", "Ein kreativer Mix", "Spielt keine Rolle"] },
    { question: "Wie wichtig ist es Ihnen, durch Ihre Arbeit anderen oder der Gesellschaft zu helfen?", options: ["Extrem wichtig", "Ziemlich wichtig", "Ein nettes Extra", "Keine meiner Prioritäten"] },
    { question: "Was ist Ihr Entscheidungsstil?", options: ["Analytisch, basierend auf Daten", "Intuitiv, basierend auf meinem Bauchgefühl", "Kollaborativ, nach Rücksprache mit anderen", "Schnell und entschlossen"] },
    { question: "Welcher dieser Faktoren ist Ihnen in einer idealen Arbeitsumgebung am wichtigsten?", options: ["Autonomie und Freiheit bei der Ausführung meiner Arbeit.", "Ein unterstützendes, kooperatives Team und ein positives soziales Umfeld.", "Klare Aufstiegs- und Karriereentwicklungsmöglichkeiten innerhalb des Unternehmens.", "Arbeit an innovativen, marktführenden Produkten oder Dienstleistungen."] },
    { question: "Was hoffen Sie in den nächsten fünf Jahren zu erreichen?", options: ["Finanzielle Stabilität und ein Zuhause", "Erfahrung und schnelles berufliches Wachstum", "Ein Handwerk oder eine Fähigkeit meistern", "Mein eigenes Unternehmen gründen"] },
    { type: 'text', question: "Beschreiben Sie eine Situation, in der Sie schnell eine neue technische Fähigkeit erlernen mussten, um ein Projekt abzuschließen. Welche Schritte haben Sie unternommen und was war das Ergebnis?" },
    { type: 'text', question: "Wie stellen Sie sich angesichts Ihrer beruflichen Ziele die Integration Ihres Berufs- und Privatlebens in 5 Jahren vor? Welche Art von Flexibilität benötigen Sie, um dies zu erreichen?" },
  ],
  tr: [
    { type: 'text', id: 'name', question: "Başlayalım, adınız nedir?" },
    { type: 'number', id: 'age', question: "Kaç yaşındasınız?" },
    { question: "Hangi çalışma ortamını tercih edersiniz?", options: ["Sakin, düzenli bir ofis", "Dinamik, değişen bir ortam", "Açık hava veya hareket halinde", "Atölye veya laboratuvar"] },
    { question: "En çok ne tür görevlerden hoşlanırsınız?", options: ["Karmaşık sorunları çözmek ve analiz etmek", "Yaratıcı olmak ve yeni şeyler tasarlamak", "İnsanlara yardım etmek ve destek olmak", "Hassas bir şekilde organize etmek ve planlamak"] },
    { question: "Çalışma tarzınızı nasıl tanımlarsınız?", options: ["En iyi tek başıma çalışırım", "Takım içinde çalışmaktan hoşlanırım", "Takımlara ve projelere liderlik etmeyi severim", "Gereken her tarza uyum sağlarım"] },
    { question: "Yüksek bir maaş sizin için ne kadar önemli?", options: ["Çok önemli, önceliğim bu", "Önemli, ama her şey değil", "Orta derecede önemli", "Daha az maaşla sevdiğim bir işi tercih ederim"] },
    { question: "İşteki temel motivasyonunuz nedir?", options: ["Başarı ve hedeflere ulaşmak", "Sürekli yeni beceriler öğrenmek", "Toplumda olumlu bir etki yaratmak", "İstikrar ve iş güvencesi"] },
    { question: "Baskı ve son teslim tarihleriyle nasıl başa çıkarsınız?", options: ["Baskı altında daha iyi çalışırım", "İyi ve organize bir şekilde yönetirim", "Biraz strese girerim ama işi bitiririm", "Stressiz bir ortamı tercih ederim"] },
    { question: "İş yerinde daha önce hiç karşılaşmadığınız karmaşık bir teknik sorunla karşılaştınız. İlk adımınız ne olur?", options: ["İnternette çözüm ararım ve teknik dokümanları kendi başıma okurum.", "Hemen daha deneyimli bir meslektaşımdan veya yöneticimden yardım isterim.", "Neyin işe yaradığını görmek için farklı çözümleri doğrudan denerim (deneme yanılma).", "Başlamadan önce sorunu daha küçük parçalara ayırır ve her birini analiz ederim."] },
    { question: "Mevcut Almanca seviyeniz nedir?", options: ["Hiç bilmiyorum (A0)", "Başlangıç (A1/A2)", "Orta (B1/B2)", "İleri (C1/C2)", "Anadil"] },
    { question: "En yüksek eğitim yeterliliğiniz nedir?", options: ["Lise altı", "Lise diploması", "Diploma veya mesleki eğitim", "Üniversite diploması veya üstü"] },
    { question: "Veri ve rakamlarla mı yoksa fikir ve kavramlarla mı çalışmayı tercih edersiniz?", options: ["Veri ve rakamlar", "Fikirler ve kavramlar", "İkisinin bir karışımı", "Hiçbiri"] },
    { question: "İşinizde yaratıcılık ne kadar önemli?", options: ["Vazgeçilmez ve merkezi", "Önemli ve bazen gerekli", "Güzel bir artı ama zorunlu değil", "Hiç önemli değil"] },
    { question: "Rutin ve tekrarlayan görevlerle nasıl başa çıkarsınız?", options: ["Hoşlanırım, rahatlatıcı bulurum", "İşin bir parçası olarak tolere ederim", "Aşırı sıkıcı bulurum", "Otomatikleştirmeye veya devretmeye çalışırım"] },
    { question: "Ekibinize önemli ve karmaşık bir fikri iletmeniz gerektiğinde, hangi yöntemi tercih edersiniz?", options: ["Ayrıntılı bir e-posta veya kapsamlı bir belge yazmak.", "Bir toplantı düzenleyip görsel bir sunum yapmak.", "Fikri her ekip üyesiyle bireysel olarak tartışmak.", "Etkileşimli bir şekilde açıklamak için bir beyaz tahta veya görsel araç kullanmak."] },
    { question: "Bir grupta genellikle hangi rolü üstlenirsiniz?", options: ["Lider", "Analist ve planlamacı", "Barış sağlayıcı ve takım koordinörü", "Pratik uygulayıcı"] },
    { question: "Bu becerilerden hangisi sizi en iyi tanımlar?", options: ["Eleştirel düşünme", "Etkili iletişim", "El becerisi", "Empati ve başkalarını anlama"] },
    { question: "Becerilerinizi geliştirmek için bir fırsatınız var. Hangi seçeneği seçersiniz?", options: ["Mevcut alanımda tanınmış bir sertifika almak için ileri düzey bir eğitim kursu.", "Yeteneklerimi zorlayan ve tamamen farklı beceriler öğrenmemi gerektiren yeni bir proje.", "Uzmanlarla ağ kurmak için konferanslara ve atölye çalışmalarına katılmak.", "Yeni başlayanlara öğretmek için bir mentor rolü üstlenmek."] },
    { question: "Belirgin bir kariyer yolunu mu yoksa kendi rolünüzü şekillendirmenize izin veren bir işi mi tercih edersiniz?", options: ["Belirgin kariyer yolu", "Kendi rolümü şekillendirmek", "Belirgin bir tercihim yok", "Emin değilim"] },
    { question: "İşinizde fiziksel çalışma ne kadar önemli?", options: ["Fiziksel olarak aktif bir işi tercih ederim", "Biraz fiziksel aktivite sorun değil", "Ağırlıklı olarak bir ofis işini tercih ederim", "Tamamen bir ofis işi olmalı"] },
    { question: "Yapıcı eleştirilerle nasıl başa çıkarsınız?", options: ["Değer veririm ve aktif olarak ararım", "Kabul eder ve ondan öğrenirim", "Başlangıçta biraz savunmacı olurum", "Zor ve moral bozucu bulurum"] },
    { question: "Büyük resme mi yoksa ince detaylara mı odaklanan birisiniz?", options: ["Büyük resim ve strateji", "İnce detaylar ve uygulama", "İkisi arasında kolayca geçiş yapabilirim", "Emin değilim"] },
    { question: "Şirket aniden ana stratejisini değiştirmeye karar verdi ve bu durum projenizi doğrudan etkiliyor. Nasıl tepki verirsiniz?", options: ["Harcanan çaba için hayal kırıklığına uğrarım, ancak yeni yöne uyum sağlarım.", "Değişikliğin arkasındaki nedenleri ve projemin yeni stratejiye nasıl uyabileceğini hemen anlamaya çalışırım.", "Yeni bir şey düşünmeden önce eski projenin kalan görevlerini bitirmeye odaklanırım.", "Bunu yeni stratejiyle uyumlu yeni fikirler önermek için bir fırsat olarak görürüm."] },
    { question: "Resmi mi yoksa gayriresmi bir çalışma ortamını mı tercih edersiniz?", options: ["Resmi ve yapılandırılmış", "Gayriresmi ve rahat", "Yaratıcı bir karışım", "Fark etmez"] },
    { question: "İşiniz aracılığıyla başkalarına veya topluma yardım etmek sizin için ne kadar önemli?", options: ["Son derece önemli", "Olduça önemli", "Hoş bir eklenti", "Önceliklerimden biri değil"] },
    { question: "Karar verme tarzınız nedir?", options: ["Analitik, verilere dayalı", "Sezgisel, içgüdülerime dayalı", "İşbirlikçi, başkalarına danıştıktan sonra", "Hızlı ve kararlı"] },
    { question: "İdeal bir çalışma ortamında bu faktörlerden hangisi sizin için EN ÖNEMLİSİDİR?", options: ["İşimi nasıl yapacağım konusunda özerklik ve özgürlük.", "Destekleyici, işbirlikçi bir ekip ve pozitif bir sosyal ortam.", "Şirket içinde terfi ve kariyer gelişimi için net fırsatlar.", "Yenilikçi, pazar lideri ürünler veya hizmetler üzerinde çalışmak."] },
    { question: "Önümüzdeki beş yıl içinde neyi başarmayı umuyorsunuz?", options: ["Finansal istikrar ve bir ev", "Deneyim ve hızlı profesyonel büyüme", "Bir zanaat veya beceride ustalaşmak", "Kendi işimi kurmak"] },
    { type: 'text', question: "Bir projeyi tamamlamak için hızlı bir şekilde yeni bir teknik beceri öğrenmeniz gereken bir durumu anlatın. Hangi adımları attınız ve sonuç ne oldu?" },
    { type: 'text', question: "Kariyer hedeflerinizi göz önünde bulundurarak, 5 yıl sonra kariyer hayatınızın kişisel hayatınızla nasıl bütünleştiğini hayal ediyorsunuz? Bunu başarmak için ne tür bir esnekliğe ihtiyacınız var?" },
  ],
  uk: [
    { type: 'text', id: 'name', question: "Почнемо, як вас звати?" },
    { type: 'number', id: 'age', question: "Скільки вам років?" },
    { question: "Якому робочому середовищу ви віддаєте перевагу?", options: ["Тихий, організований офіс", "Динамічне, мінливе середовище", "На відкритому повітрі або в дорозі", "Майстерня або лабораторія"] },
    { question: "Які завдання вам подобаються найбільше?", options: ["Вирішення складних проблем та аналіз", "Творчість та створення нового", "Допомога та підтримка людей", "Точна організація та планування"] },
    { question: "Як би ви описали свій стиль роботи?", options: ["Я найкраще працюю наодинці", "Мені подобається працювати в команді", "Я люблю керувати командами та проектами", "Я адаптуюся до будь-якого стилю"] },
    { question: "Наскільки для вас важлива висока зарплата?", options: ["Дуже важлива, це мій пріоритет", "Важлива, але не найголовніше", "Помірно важлива", "Я віддаю перевагу улюбленій роботі з меншою зарплатою"] },
    { question: "Яка ваша основна мотивація в роботі?", options: ["Досягнення та виконання цілей", "Постійне вивчення нових навичок", "Позитивний вплив на суспільство", "Стабільність та безпека робочого місця"] },
    { question: "Як ви справляєтеся з тиском і дедлайнами?", options: ["Я розквітаю під тиском", "Я добре і організовано з цим справляюся", "Я трохи нервую, але виконую роботу", "Я віддаю перевагу середовищу без стресу"] },
    { question: "Ви стикаєтеся зі складною технічною проблемою на роботі, з якою ніколи раніше не мали справи. Яким буде ваш перший крок?", options: ["Я шукаю рішення в Інтернеті та читаю технічну документацію самостійно.", "Я негайно прошу допомоги у більш досвідченого колеги або свого керівника.", "Я пробую різні рішення безпосередньо, щоб побачити, що спрацює (метод спроб і помилок).", "Я розбиваю проблему на менші частини та аналізую кожну, перш ніж почати."] },
    { question: "Який ваш поточний рівень німецької мови?", options: ["Не володію (A0)", "Початківець (A1/A2)", "Середній (B1/B2)", "Просунутий (C1/C2)", "Рідна мова"] },
    { question: "Яка ваша найвища освітня кваліфікація?", options: ["Нижче середньої", "Атестат про середню освіту", "Диплом або професійне навчання", "Вища освіта або вище"] },
    { question: "Ви віддаєте перевагу роботі з даними та цифрами чи з ідеями та концепціями?", options: ["Дані та цифри", "Ідеї та концепції", "Суміш обох", "Жодне з них"] },
    { question: "Наскільки важлива творчість у вашій роботі?", options: ["Незамінна і центральна", "Важлива і іноді потрібна", "Приємний бонус, але не обов'язкова", "Зовсім не важлива"] },
    { question: "Як ви ставитеся до рутинних, повторюваних завдань?", options: ["Мені вони подобаються, вони заспокоюють", "Я терплю їх як частину роботи", "Вони мені здаються надзвичайно нудними", "Я намагаюся їх автоматизувати або делегувати"] },
    { question: "Коли вам потрібно донести важливу та складну ідею до вашої команди, якому методу ви віддаєте перевагу?", options: ["Написати детальний електронний лист або вичерпний документ.", "Провести зустріч і зробити візуальну презентацію.", "Обговорити ідею індивідуально з кожним членом команди.", "Використовувати дошку або візуальний інструмент для інтерактивного пояснення."] },
    { question: "Яку роль ви зазвичай граєте в групі?", options: ["Лідер", "Аналітик і планувальник", "Миротворець і координатор команди", "Практичний виконавець"] },
    { question: "Яка з цих навичок найкраще вас описує?", options: ["Критичне мислення", "Ефективна комунікація", "Спритність рук", "Емпатія та розуміння інших"] },
    { question: "У вас є можливість розвинути свої навички. Який варіант ви оберете?", options: ["Просунутий навчальний курс для отримання визнаного сертифіката в моїй поточній галузі.", "Новий проект, який кидає виклик моїм здібностям і вимагає вивчення абсолютно інших навичок.", "Відвідування конференцій та семінарів для спілкування з експертами.", "Взяти на себе роль наставника для навчання новачків."] },
    { question: "Ви віддаєте перевагу чіткому кар'єрному шляху чи роботі, де ви можете формувати власну роль?", options: ["Чіткий кар'єрний шлях", "Формувати власну роль", "Немає сильних переваг", "Я не впевнений"] },
    { question: "Наскільки важлива фізична праця у вашій роботі?", options: ["Я віддаю перевагу фізично активній роботі", "Невелика фізична активність - це нормально", "Я віддаю перевагу в основному офісній роботі", "Це має бути виключно офісна робота"] },
    { question: "Як ви ставитеся до конструктивної критики?", options: ["Я ціную її і активно шукаю", "Я приймаю її і вчуся на ній", "Спочатку я трохи захищаюся", "Мені важко і це демотивує"] },
    { question: "Ви людина, яка зосереджується на загальній картині чи на дрібних деталях?", options: ["Загальна картина та стратегія", "Дрібні деталі та виконання", "Я можу легко переключатися між ними", "Я не впевнений"] },
    { question: "Компанія раптово вирішує змінити свою основну стратегію, що безпосередньо впливає на ваш проект. Як ви реагуєте?", options: ["Я відчуваю розчарування через змарновані зусилля, але адаптуюся до нового напрямку.", "Я негайно намагаюся зрозуміти причини змін і як мій проект може вписатися в нову стратегію.", "Я зосереджуюся на завершенні завдань старого проекту, перш ніж думати про щось нове.", "Я бачу в цьому можливість запропонувати нові ідеї, які відповідають новій стратегії."] },
    { question: "Ви віддаєте перевагу формальному чи неформальному робочому середовищу?", options: ["Формальне та структуроване", "Неформальне та розслаблене", "Творчий мікс", "Не має значення"] },
    { question: "Наскільки важливо для вас допомагати іншим або суспільству через свою роботу?", options: ["Надзвичайно важливо", "Досить важливо", "Приємний бонус", "Не в моїх пріоритетах"] },
    { question: "Який ваш стиль прийняття рішень?", options: ["Аналітичний, на основі даних", "Інтуїтивний, на основі почуттів", "Колаборативний, після консультацій з іншими", "Швидкий і рішучий"] },
    { question: "Який із цих факторів є для вас НАЙВАЖЛИВІШИМ в ідеальному робочому середовищі?", options: ["Автономія та свобода у виконанні моєї роботи.", "Підтримуюча, співпрацююча команда та позитивне соціальне середовище.", "Чіткі можливості для просування та кар'єрного росту всередині компанії.", "Робота над інноваційними, провідними на ринку продуктами чи послугами."] },
    { question: "Чого ви сподіваєтеся досягти в найближчі п'ять років?", options: ["Фінансової стабільності та житла", "Досвіду та швидкого професійного зростання", "Оволодіти ремеслом або навичкою", "Запустити власний бізнес"] },
    { type: 'text', question: "Опишіть ситуацію, коли вам потрібно було швидко опанувати нову технічну навичку для завершення проекту. Які кроки ви зробили, і яким був результат?" },
    { type: 'text', question: "Враховуючи ваші професійні цілі, як ви уявляєте інтеграцію вашої кар'єри з особистим життям через 5 років? Яка гнучкість вам потрібна для цього?" },
  ]
};

// NOTE: This list now contains 10 curated professions.
export const professions = [
    {
        type: 'ausbildung',
        title: { ar: "فني ميكاترونيك", de: "Mechatroniker/in", tr: "Mekatronik Teknisyeni", uk: "Мехатронік" },
        duration: { ar: "3.5 سنوات", de: "3,5 Jahre", tr: "3,5 yıl", uk: "3,5 роки" },
        salary: { ar: "€950 - €1,200/شهريا (أثناء التدريب)", de: "€950 - €1.200/Monat (in Ausbildung)", tr: "€950 - €1,200/ay (eğitim sırasında)", uk: "€950 - €1,200/місяць (під час навчання)" },
        requirements: { ar: "شهادة Realschulabschluss", de: "Realschulabschluss", tr: "Ortaokul diploması", uk: "Атестат про середню освіту (Realschulabschluss)" },
        duties: { ar: "بناء وتجميع وتركيب الأنظمة الميكانيكية والإلكترونية.", de: "Mechanische und elektronische Systeme bauen, montieren und installieren.", tr: "Mekanik ve elektronik sistemleri kurmak, monte etmek ve kurmak.", uk: "Створення, монтаж та встановлення механічних та електронних систем." },
        videoUrl: "https://www.youtube-nocookie.com/embed/501a_I2P2oM"
    },
    {
        type: 'ausbildung',
        title: { ar: "ممرض/ة", de: "Pflegefachmann/-frau", tr: "Hemşire", uk: "Медсестра/Медбрат" },
        duration: { ar: "3 سنوات", de: "3 Jahre", tr: "3 yıl", uk: "3 роки" },
        salary: { ar: "€1,100 - €1,300/شهريا (أثناء التدريب)", de: "€1.100 - €1.300/Monat (in Ausbildung)", tr: "€1,100 - €1,300/ay (eğitim sırasında)", uk: "€1,100 - €1,300/місяць (під час навчання)" },
        requirements: { ar: "شهادة Realschulabschluss، مستوى B2 في اللغة الألمانية", de: "Realschulabschluss, Deutsch B2", tr: "Ortaokul diploması, B2 Almanca", uk: "Атестат Realschulabschluss, німецька B2" },
        duties: { ar: "رعاية المرضى، إعطاء الأدوية، المساعدة في الفحوصات.", de: "Patienten betreuen, Medikamente verabreichen, bei Untersuchungen helfen.", tr: "Hastaların bakımı, ilaçların verilmesi, muayenelere yardımcı olmak.", uk: "Догляд за пацієнтами, введення ліків, допомога при обстеженнях." },
        videoUrl: "https://www.youtube-nocookie.com/embed/xL-b_sOQ2-M"
    },
    {
        type: 'job',
        title: { ar: "مطور برمجيات", de: "Softwareentwickler/in", tr: "Yazılım Geliştirici", uk: "Розробник програмного забезпечення" },
        duration: { ar: "غير محدد (وظيفة بدوام كامل)", de: "Unbefristet (Vollzeitstelle)", tr: "Süresiz (Tam zamanlı iş)", uk: "Безстроково (повна зайнятість)" },
        salary: { ar: "€45,000 - €70,000/سنويا", de: "€45.000 - €70.000/Jahr", tr: "€45,000 - €70,000/yıl", uk: "€45,000 - €70,000/рік" },
        requirements: { ar: "شهادة جامعية في علوم الحاسوب، خبرة في لغات البرمجة", de: "Studium der Informatik, Erfahrung mit Programmiersprachen", tr: "Bilgisayar Bilimleri bölümünden mezun, programlama dillerinde deneyim", uk: "Вища освіта в галузі комп'ютерних наук, досвід роботи з мовами програмування" },
        duties: { ar: "تصميم وتطوير واختبار تطبيقات البرمجيات.", de: "Entwerfen, Entwickeln und Testen von Softwareanwendungen.", tr: "Yazılım uygulamaları tasarlamak, geliştirmek ve test etmek.", uk: "Проектування, розробка та тестування програмних додатків." },
        videoUrl: "https://www.youtube-nocookie.com/embed/gApYV-gpkjM"
    },
    {
        type: 'study',
        title: { ar: "الهندسة الميكانيكية", de: "Maschinenbau", tr: "Makine Mühendisliği", uk: "Машинобудування" },
        duration: { ar: "3 سنوات (بكالوريوس)", de: "3 Jahre (Bachelor)", tr: "3 yıl (Lisans)", uk: "3 роки (Бакалавр)" },
        salary: { ar: "غير مطبق (دراسة)", de: "N/A (Studium)", tr: "Uygulanamaz (Üniversite)", uk: "Не застосовується (Навчання)" },
        requirements: { ar: "شهادة الثانوية العامة (Abitur)، مهارات قوية في الرياضيات والفيزياء", de: "Abitur, starke Mathematik- und Physikkenntnisse", tr: "Lise diploması (Abitur), güçlü matematik ve fizik becerileri", uk: "Атестат про повну загальну середню освіту (Abitur), сильні навички з математики та фізики" },
        duties: { ar: "دراسة تصميم وتطوير وتشغيل الآلات والأنظمة.", de: "Studium der Konstruktion, Entwicklung und des Betriebs von Maschinen und Anlagen.", tr: "Makinelerin ve sistemlerin tasarımı, geliştirilmesi ve işletilmesi üzerine eğitim.", uk: "Вивчення проектування, розробки та експлуатації машин і систем." },
        videoUrl: "https://www.youtube-nocookie.com/embed/Q0j_v-04iW4"
    },
     {
        type: 'job',
        title: { ar: "أخصائي لوجستيات", de: "Fachkraft für Lagerlogistik", tr: "Lojistik Uzmanı", uk: "Спеціаліст з логістики" },
        duration: { ar: "3 سنوات (تدريب مهني)", de: "3 Jahre (Ausbildung)", tr: "3 yıl (Mesleki Eğitim)", uk: "3 роки (професійне навчання)" },
        salary: { ar: "€900 - €1,100/شهريا (أثناء التدريب)", de: "€900 - €1.100/Monat (in Ausbildung)", tr: "€900 - €1.100/ay (eğitim sırasında)", uk: "€900 - €1.100/місяць (під час навчання)" },
        requirements: { ar: "شهادة Realschulabschluss", de: "Realschulabschluss", tr: "Ortaokul diploması", uk: "Атестат Realschulabschluss" },
        duties: { ar: "استلام وتخزين وشحن البضائع، إدارة المخزون.", de: "Waren annehmen, lagern und versenden, Bestandsverwaltung.", tr: "Malları teslim almak, depolamak ve göndermek, envanter yönetimi.", uk: "Прийом, зберігання та відправка товарів, управління запасами." },
        videoUrl: "https://www.youtube-nocookie.com/embed/w-0z-hAU3yU"
    },
    {
        type: 'ausbildung',
        title: { ar: "طاهي/طاهية", de: "Koch/Köchin", tr: "Aşçı", uk: "Кухар" },
        duration: { ar: "3 سنوات", de: "3 Jahre", tr: "3 yıl", uk: "3 роки" },
        salary: { ar: "€800 - €1,100/شهريا (أثناء التدريب)", de: "€800 - €1.100/Monat (in Ausbildung)", tr: "€800 - €1.100/ay (eğitim sırasında)", uk: "€800 - €1.100/місяць (під час навчання)" },
        requirements: { ar: "شهادة Hauptschulabschluss، شغف بالطعام", de: "Hauptschulabschluss, Leidenschaft für Essen", tr: "İlköğretim diploması, yemek tutkusu", uk: "Атестат про базову середню освіту (Hauptschulabschluss), пристрасть до їжі" },
        duties: { ar: "تحضير وطهي وتقديم الأطباق المختلفة.", de: "Zubereitung, Kochen und Anrichten von verschiedenen Gerichten.", tr: "Çeşitli yemekleri hazırlamak, pişirmek ve sunmak.", uk: "Підготовка, приготування та подача різноманітних страв." },
        videoUrl: "https://www.youtube-nocookie.com/embed/lnTyByz4d64"
    },
    {
        type: 'ausbildung',
        title: { ar: "متخصص تكنولوجيا المعلومات - تطوير التطبيقات", de: "Fachinformatiker/in - Anwendungsentwicklung", tr: "Bilişim Uzmanı - Uygulama Geliştirme", uk: "ІТ-спеціаліст - Розробка додатків" },
        duration: { ar: "3 سنوات", de: "3 Jahre", tr: "3 yıl", uk: "3 роки" },
        salary: { ar: "€1,000 - €1,200/شهريا (أثناء التدريب)", de: "€1.000 - €1.200/Monat (in Ausbildung)", tr: "€1.000 - €1.200/ay (eğitim sırasında)", uk: "€1.000 - €1.200/місяць (під час навчання)" },
        requirements: { ar: "شهادة Abitur أو Realschulabschluss", de: "Abitur oder Realschulabschluss", tr: "Lise veya ortaokul diploması", uk: "Abitur або Realschulabschluss" },
        duties: { ar: "تصميم وتطوير تطبيقات البرمجيات المخصصة.", de: "Maßgeschneiderte Softwareanwendungen konzipieren und entwickeln.", tr: "Özel yazılım uygulamaları tasarlamak ve geliştirmek.", uk: "Розробка та проектування індивідуальних програмних додатків." },
        videoUrl: "https://www.youtube-nocookie.com/embed/lgyaXj0c_iQ"
    },
    {
        type: 'ausbildung',
        title: { ar: "موظف إدارة المكاتب", de: "Kaufmann/-frau für Büromanagement", tr: "Ofis Yönetimi Asistanı", uk: "Клерк з управління офісом" },
        duration: { ar: "3 سنوات", de: "3 Jahre", tr: "3 yıl", uk: "3 роки" },
        salary: { ar: "€900 - €1,150/شهريا (أثناء التدريب)", de: "€900 - €1.150/Monat (in Ausbildung)", tr: "€900 - €1.150/ay (eğitim sırasında)", uk: "€900 - €1.150/місяць (під час навчання)" },
        requirements: { ar: "شهادة Realschulabschluss، مهارات تنظيمية", de: "Realschulabschluss, Organisationstalent", tr: "Ortaokul diploması, organizasyon becerileri", uk: "Атестат Realschulabschluss, організаційні навички" },
        duties: { ar: "تنظيم المهام المكتبية، المراسلات، المحاسبة.", de: "Büroaufgaben organisieren, Korrespondenz, Buchhaltung.", tr: "Ofis işlerini organize etmek, yazışmalar, muhasebe.", uk: "Організація офісних завдань, листування, бухгалтерія." },
        videoUrl: "https://www.youtube-nocookie.com/embed/G6jWbY_o_Tg"
    },
    {
        type: 'study',
        title: { ar: "العمل الاجتماعي", de: "Soziale Arbeit", tr: "Sosyal Hizmetler", uk: "Соціальна робота" },
        duration: { ar: "3.5 سنوات (بكالوريوس)", de: "3,5 Jahre (Bachelor)", tr: "3,5 yıl (Lisans)", uk: "3,5 роки (Бакалавр)" },
        salary: { ar: "غير مطبق (دراسة)", de: "N/A (Studium)", tr: "Uygulanamaz (Üniversite)", uk: "Не застосовується (Навчання)" },
        requirements: { ar: "شهادة الثانوية الفنية (Fachabitur) أو Abitur", de: "Fachabitur oder Abitur", tr: "Meslek lisesi veya lise diploması", uk: "Fachabitur або Abitur" },
        duties: { ar: "دراسة أساليب مساعدة الأفراد والأسر في المواقف الصعبة.", de: "Studium von Methoden zur Unterstützung von Einzelpersonen und Familien in schwierigen Situationen.", tr: "Zor durumlardaki bireylere ve ailelere destek yöntemleri üzerine eğitim.", uk: "Вивчення методів допомоги окремим особам та сім'ям у складних ситуациях." },
        videoUrl: "https://www.youtube-nocookie.com/embed/U3i5_Mh-hQ0"
    },
    {
        type: 'job',
        title: { ar: "مهندس مدني", de: "Bauingenieur/in", tr: "İnşaat Mühendisi", uk: "Інженер-будівельник" },
        duration: { ar: "غير محدد", de: "Unbefristet", tr: "Süresiz", uk: "Безстроково" },
        salary: { ar: "€50,000 - €70,000/سنويا", de: "€50.000 - €70.000/Jahr", tr: "€50,000 - €70,000/yıl", uk: "€50,000 - €70,000/рік" },
        requirements: { ar: "شهادة جامعية في الهندسة المدنية", de: "Studienabschluss im Bauingenieurwesen", tr: "İnşaat Mühendisliği bölümü mezunu", uk: "Вища освіта в галузі цивільного будівництва" },
        duties: { ar: "تصميم وإدارة مشاريع البناء والبنية التحتية.", de: "Bau- und Infrastrukturprojekte entwerfen und leiten.", tr: "İnşaat ve altyapı projeleri tasarlamak ve yönetmek.", uk: "Проектування та управління будівельними та інфраструктурними проектами." },
        videoUrl: "https://www.youtube-nocookie.com/embed/v9xU-n1rP1A"
    }
];