// Define high-quality, consistent SVG flags for all languages.
const syrianOppositionFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzAwN2EzZCIvPjxyZWN0IHk9IjIwMCIgd2lkdGg9IjkwMCIgaGVpZGhtPSIyMDAiIGZpbGw9IiNmZmYiLz48cmVjdCB5PSI0MDAiIHdpZHRoPSI5MDAiIGhlaWdodD0iMjAwIiBmaWxsPSIjMDAwIi8+PGcgZmlsbD0iI2NlMTEyNiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDUwIDMwMCkgc2NhbGUoMjIpIj48ZyBpZD0icyI+PHBhdGggZD0iTTAtMi4zNzc1bDEuNTQ1IDQuNzU1LTQuMDcyLTIuOTM5aDUuMDU0TC0xLjU0NSAyLjM4eiIvPjwvZz48dXNlIGhyZWY9IiNzIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTIpIi8+PHVzZSBocmVmPSIjcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCkiLz48dXNlIGhyZWY9IiNzIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMikiLz48L2c+PC9zdmc+" alt="Syrian Flag" loading="lazy">`;
const germanFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI0ZGQ0UwMCIvPjxyZWN0IHdpZHRoPSI5MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjRDAwIi8+PHJlY3Qgd2lkdGg9IjkwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiMwMDAiLz48L3N2Zz4=" alt="German Flag" loading="lazy">`;
const britishFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2MCAzMCI+PGNsaXBQYXRoIGlkPSJhIj48cGF0aCBkPSJNMCAwdjMwaDYwVjB6Ii8+PC9jbGlwUGF0aD48Y2xpcFBhdGggaWQ9ImIiPjxwYXRoIGQ9Ik0zMCAxNWgzMHYxNWgtMzB6TTAgMTVoMzB2MTVoLTMwek0wIDBoMzB2MTVoLTMwek0zMCAwaDMwdjE1aC0zMHoiLz48L2NsaXBQYXRoPjxnIGNsaXAtcGF0aD0idXJsKCNhKSI+PHBhdGggZD0iTTAgMHYzMGg2MFYweiIgZmlsbD0iIzAxMjE2OSIvPjxwYXRoIGQ9Ik0wIDBsNjAgMzBtMC0zMEwwIDMwIiBzdHJva2U9IiNmZmYiIHN0cm9rZS13aWR0aD0iNiIvPjxwYXRoIGQ9Ik0wIDBsNjAgMzBtMC0zMEwwIDMwIiBjbGlwLXBhdGg9InVybCgjYikiIHN0cm9rZT0iI0M4MTAyRSIgc3Ryb2tlLXdpZHRoPSI0Ii8+PHBhdGggZD0iTTMwIDB2MzBNMCAxNWg2MCIgc3Ryb2tlPSIjZmZmIiBzdHJva2Utd2lkdGg9IjEwIi8+PHBhdGggZD0iTTMwIDB2MzBNMCAxNWg2MCIgc3Ryb2tlPSIjQzgxMDJFIiBzdHJva2Utd2lkdGg9IjYiLz48L2c+PC9zdmc+" alt="British Flag" loading="lazy">`;
const turkishFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5MDAgNjAwIj48cmVjdCB3aWR0aD0iOTAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI2UzMGExNyIvPjxjaXJjbGUgY3g9IjI3NSIgY3k9IjMwMCIgcj0iMTUwIiBmaWxsPSIjZmZmIi8+PGNpcmNsZSBjeD0iMzEyLjUiIGN5PSIzMDAiIHI9IjEyMCIgZmlsbD0iI2UzMGExNyIvPjxwYXRoIGQ9Ik00MjUgMzAwbDExOS41LTM2LjctNzMuOSA5Ni4xVjI0MC42bC03My45IDk2LjF6IiBmaWxsPSIjZmZmIi8+PC9zdmc+" alt="Turkish Flag" loading="lazy">`;
const ukrainianFlagImg = `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzIDIiPjxyZWN0IHdpZHRoPSIzIiBoZWlnaHQ9IjEiIGZpbGw9IiMwMDU3QjciLz48cmVjdCB5PSIxIiB3aWR0aD0iMyIgaGVpZ2h0PSIxIiBmaWxsPSIjRkZENzAwIi8+PC9zdmc+" alt="Ukrainian Flag" loading="lazy">`;

export const translations = {
  ar: {
    langName: `${syrianOppositionFlagImg} العربية`,
    dir: "rtl",
    headerTitle: "توجيه مهني مع Ahmad Mrashaha",
    footerText: "© 2025 - تم التطوير بواسطة Ahmad Mrashaha لمساعدتك في العثور على طريقك.",
    welcomeTitle: "اكتشف مسارك المهني المثالي في ألمانيا",
    welcomeDesc: "أجب على 30 سؤالاً دقيقاً حول شخصيتك، مهاراتك، وطموحاتك. سيقوم الذكاء الاصطناعي لدينا بتحليل إجاباتك بعمق لاقتراح أفضل المسارات المهنية، التدريب المهني (Ausbildung)، أو المسارات الدراسية لك.",
    startQuiz: "ابدأ اختبار التوجيه المهني",
    startQuizDesc: "أجب على أسئلتنا المصممة خصيصًا واحصل على تحليل شخصي لمسارك المهني.",
    browseProfessions: "تصفح المهن",
    browseProfessionsDesc: "استكشف قاعدة بياناتنا للمهن والتدريب المهني والمسارات الدراسية.",
    searchAvailableJobs: "ابحث عن وظائف متاحة",
    searchAvailableJobsDesc: "ابحث عن فرص عمل حقيقية متاحة الآن في جميع أنحاء ألمانيا.",
    searchForPraktikum: "ابحث عن تدريب عملي (Praktikum)",
    searchForPraktikumDesc: "اعثر على فرص تدريب عملي وأنشئ رسائل بريد إلكتروني احترافية لتقديم طلبك.",
    createResume: "إنشاء سيرة ذاتية (CV)",
    createResumeDesc: "أجب على بعض الأسئلة وسنقوم بإنشاء سيرة ذاتية احترافية لك.",
    professionsDesc: "ابحث وتصفح فرص العمل والتدريب المهني والدراسة الجامعية في ألمانيا.",
    quizIntroTitle: "قبل أن تبدأ",
    quizIntroDesc: "يتكون هذا الاختبار من 30 سؤالاً حول شخصيتك ومهاراتك وطموحاتك. ستساعدنا إجاباتك الصادقة في إنشاء تقرير مفصل مع اقتراحات مهنية مخصصة. لا توجد إجابات صحيحة أو خاطئة، فقط كن على طبيعتك!",
    quizIntroStartBtn: "ابدأ الاختبار",
    back: "الخلف",
    next: "التالي",
    getResults: "احصل على نتائجي",
    loadingTitle: "جاري تحليل شخصيتك...",
    loadingDesc: "يقوم الذكاء الاصطناعي بإعداد تقريرك المهني المفصل. قد يستغرق هذا بضع لحظات.",
    resultsTitleFor: "تقريرك المهني لـ {name}",
    you: "لك",
    personalitySummary: "تحليل شخصيتك المهنية",
    recommendedPaths: "المسارات المهنية الموصى بها",
    careerAdvice: "نصائح مهنية مخصصة",
    restart: "العودة للرئيسية",
    searchPlaceholder: "ابحث عن مهنة...",
    all: "الكل",
    ausbildung: "تدريب مهني",
    study: "دراسة",
    job: "وظيفة",
    duration: "المدة",
    salary: "الراتب",
    requirements: "المتطلبات",
    duties: "الواجبات",
    skillsRequired: "المهارات المطلوبة",
    home: "الرئيسية",
    errorText: "عذراً، حدث خطأ أثناء إنشاء نتائجك. يرجى المحاولة مرة أخرى لاحقاً.",
    answerHere: "اكتب إجابتك هنا...",
    page: "صفحة",
    printReport: "طباعة التقرير",
    emailReport: "إرسال عبر الإيميل",
    saveReport: "حفظ النتائج",
    reportSaved: "تم الحفظ!",
    emailSubject: "تقريري المهني من موقع توجيه مهني",
    jobSearchDesc: "استخدم الذكاء الاصطناعي للبحث عن وظائف أو فرص تدريب مهني متاحة حالياً في ألمانيا. أدخل المسمى الوظيفي والموقع للحصول على نتائج مباشرة.",
    jobTitlePlaceholder: "مثال: مطور برمجيات، ممرض...",
    locationPlaceholder: "مثال: برلين، هامبورغ...",
    search: "بحث",
    jobSearchLoading: "جاري البحث عن وظائف متاحة...",
    jobSearchSources: "عروض العمل المتاحة (المصادر)",
    jobSearchPrompt: "باستخدام بحث جوجل، ابحث عن وظائف أو فرص تدريب مهني (Ausbildung) متاحة حالياً لـ '{jobTitle}' في أو بالقرب من '{location}'، ألمانيا. لا تقدم ملخصًا. قدم فقط روابط المصدر الأصلية التي وجدتها.",
    noJobsFound: "لم يتم العثور على عروض عمل مطابقة.",
    savedReportsTitle: "التقارير المحفوظة",
    anonymousReport: "تقرير بدون اسم",
    viewDetails: "عرض التفاصيل",
    delete: "حذف",
    confirmDeleteReport: "هل أنت متأكد أنك تريد حذف هذا التقرير؟",
    noSavedReports: "لا يوجد تقارير محفوظة بعد.",
    adminLogin: "دخول المسؤول",
    responsibleLogin: "دخول المسؤول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صالحة.",
    logout: "تسجيل الخروج",
    praktikumDesc: "هل تبحث عن تدريب عملي (Praktikum)؟ أدخل المجال الذي تهتم به والمدينة، وسيقوم الذكاء الاصطناعي بالبحث عن شركات مناسبة لك. اختر واحدة، ثم أنشئ مسودة بريد إلكتروني احترافية للاستفسار.",
    fieldPlaceholder: "مثال: تكنولوجيا المعلومات، تسويق، هندسة...",
    yourNamePlaceholder: "اسمك الكامل",
    praktikumSearchBtn: "ابحث عن شركات",
    praktikumCompanyLoading: "جاري البحث عن فرص تدريب...",
    praktikumCompanyResult: "الشركات المقترحة",
    company: "الشركة",
    location: "الموقع",
    select: "اختر",
    selected: "تم الاختيار",
    praktikumGenerateEmailTitle: "أنشئ بريداً إلكترونياً للاستفسار",
    praktikumGenerateEmailBtn: "أنشئ البريد الإلكتروني",
    praktikumEmailLoading: "جاري كتابة بريدك الإلكتروني...",
    praktikumYourEmail: "مسودة بريدك الإلكتروني",
    copyEmail: "نسخ البريد الإلكتروني",
    copied: "تم النسخ!",
    praktikumSearchError: "عذراً، لم نتمكن من العثور على شركات مناسبة. الرجاء محاولة البحث بمصطلحات مختلفة.",
    praktikumNoCompaniesFound: "لم يتم العثور على شركات مطابقة لبحثك. جرب تعديل مصطلحات البحث.",
    praktikumIntroTitle: "طريقك نحو التدريب العملي (Praktikum)",
    praktikumIntroDesc1: "هذه الأداة تستخدم الذكاء الاصطناعي للبحث عن شركات قد توفر فرص تدريب عملي في المجال والموقع الذي تحدده.",
    praktikumIntroDesc2: "بعد اختيار شركة، سنساعدك في إنشاء مسودة بريد إلكتروني احترافية يمكنك إرسالها للاستفسار عن فرصة. أنت من سيقوم بإرسال البريد النهائي.",
    praktikumIntroDisclaimer: "<strong>ملاحظة هامة:</strong> هذه الطريقة هي بمثابة 'طلب غير موجه' (Initiativbewerbung). هذا يعني أن الشركات التي نعثر عليها قد لا تكون قد أعلنت عن وجود شواغر للتدريب. هدفنا هو تمكينك من أخذ زمام المبادرة والتواصل بشكل احترافي، وهو ما يُقدر بشدة في سوق العمل الألماني. الفرصة ليست مضمونة 100%، لكنها خطوة استباقية ممتازة.",
    praktikumIntroStartBtn: "فهمت، لنبدأ البحث",
    praktikumSearchPrompt: "ROLE: High-precision company investigator for the German market.\n\nTASK: Find 5-7 relevant companies in or near '{location}' using Google Search that potentially offer a '{internshipType}' internship in the '{field}' sector. Prioritize official company websites over simple directory listings.\n\nCRITICAL INSTRUCTIONS:\n1.  **ABSOLUTE DATA FIDELITY**: NEVER invent information. If a piece of information (e.g., contact person, email) is NOT EXPLICITLY mentioned in the search results, the value for that field MUST be an empty string `\"\"`.\n2.  **PURE JSON FORMAT**: Your entire response MUST be exclusively a valid JSON array. No introductory text, no comments, no markdown like ```json.\n\nJSON OUTPUT STRUCTURE:\n`[{\"name\": \"Full Official Company Name\", \"address\": \"Street, Postal Code, City\", \"contactPerson\": \"\", \"applicationEmail\": \"\", \"description\": \"A single, concise sentence describing the company's main industry or activity.\", \"website\": \"Official Website URL\"}]`",
    praktikumEmailPrompt: "أنت مساعد مهني ممتاز. اكتب مسودة بريد إلكتروني احترافية ومهذبة باللغة الألمانية. البريد الإلكتروني من '{userName}' إلى '{companyName}' للاستفسار عن تدريب عملي (Praktikum) في مجال '{field}'. الغرض من التدريب هو '{internshipType}'. قم بتكييف المحتوى والنبرة بشكل دقيق جدًا ليتناسب مع نوع التدريب:\n\n- إذا كان النوع 'للمدرسة' (Schülerpraktikum): اكتب كطالب متحمس. اذكر أن هذا تدريب مدرسي إلزامي. اسأل عن الفترة الزمنية الممكنة والمستندات المطلوبة. يجب أن تكون النبرة مهذبة وشبابية.\n- إذا كان النوع 'للتوجيه المهني' (Berufsorientierung): عبر عن اهتمام قوي بالمجال '{field}' وبالشركة. اشرح أن الهدف هو اكتساب رؤى أولية وتسهيل اختيار المهنة. يجب أن تكون النبرة فضولية ومتحمسة.\n- إذا كان النوع 'للأوسبيلدونج' (Ausbildung): اكتب بشكل أكثر رسمية واحترافية. اذكر أن المتقدم يسعى للحصول على تدريب مهني في هذا المجال ويرغب في اكتساب خبرة عملية. أكّد على الدافع لتطبيق المهارات عمليًا.\n\nاستخدم دائمًا تحية مناسبة (Sehr geehrte Damen und Herren,) وصيغة ختامية (Mit freundlichen Grüßen). اسأل عن الشخص المسؤول عن استلام طلبات التقديم.",
    internshipTypeLabel: "نوع التدريب العملي",
    internshipTypePlaceholder: "اختر نوع التدريب...",
    internshipTypeSchool: "للمدرسة",
    internshipTypeAusbildung: "للأوسبيلدونج",
    internshipTypeOrientation: "للتوجيه المهني",
    loading: "جاري التحميل...",
    underMaintenanceShort: "تحت الصيانة",
    underMaintenanceTitle: "هذا القسم تحت الصيانة",
    underMaintenanceDesc: "نحن نعمل حاليًا على تحسين هذا القسم وسيكون متاحًا قريبًا. يمكن للمسؤولين فقط الوصول إليه في الوقت الحالي.",
    systemInstruction: "أنت مستشار مهني خبير ومحلل نفسي متخصص في سوق العمل الألماني. مهمتك هي تحليل إجابات المستخدم {name}، البالغ من العمر {age} عامًا، على 30 سؤالًا لتقديم تقرير مهني مفصل وشخصي للغاية باللغة العربية. يجب أن يكون تحليلك عميقًا، ومشجعًا، وعمليًا. بناءً на الإجابات، قدم تقرير JSON مفصلًا يطابق المخطط. يجب أن يتضمن التقرير تحليلًا دقيقًا للشخصية، و3-4 اقتراحات وظيفية متنوعة جدًا ومناسبة (بما في ذلك Ausbildung والدراسة)، ونصائح مهنية قابلة للتنفيذ. خاطب المستخدم باسمه. يجب أن تكون لهجتك احترافية وداعمة للغاية.",
    promptIntro: "هذه هي بياناتي وإجاباتي على استبيان التوجيه المهني:",
    promptInstruction: "يرجى تقديم تحليلي المهني المفصل بناءً على هذه الإجابات.",
    schemaPersonality: "تحليل عميق ومفصل لشخصية المستخدم المهنية، نقاط القوة، مجالات التطوير، ونمط العمل المثالي، مكتوب بنبرة احترافية ومشجعة باللغة العربية.",
    schemaJobSuggestions: "قائمة من 3-4 اقتراحات مناسبة جدًا لوظائف أو تدريب مهني (Ausbildung) أو دراسة في ألمانيا باللغة العربية.",
    schemaTitle: "اسم الوظيفة أو التدريب المهني أو الدراسة باللغة العربية.",
    schemaDescription: "شرح مفصل ومقنع لماذا يناسب هذا المسار شخصية المستخدم وإجاباته، باللغة العربية.",
    schemaDetails: "تفاصيل رئيسية عملية مثل مدة التدريب، توقعات الراتب، متطلبات اللغة، أو فرص النمو في ألمانيا. باللغة العربية.",
    schemaCompanyName: "اسم الشركة.",
    schemaCompanyAddress: "العنوان الكامل للشركة.",
    schemaCompanyContact: "رقم هاتف الشركة أو البريد الإلكتروني.",
    schemaCompanyWebsite: "الموقع الإلكتروني الرسمي للشركة.",
    viewReports: "عرض التقارير",
    companyWebsite: "الموقع الإلكتروني",
    futureProjectTitle: "مشروع مستقبلي",
    futureProjectDesc: "هذه المساحة محجوزة لميزات جديدة ومثيرة.",
    apiKeyNotConfiguredError: "خطأ في الإعداد: لم يتم العثور على مفتاح API. يرجى التأكد من إضافة متغير بيئة `API_KEY` في إعدادات النشر الخاصة بك.",
    invalidApiKeyError: "عذراً، حدث خطأ. يبدو أن مفتاح API الذي تم إعداده غير صالح أو منتهي الصلاحية. يرجى مراجعة متغيرات البيئة في إعدادات النشر الخاصة بك.",
    apiKeyStatus: "حالة مفتاح API",
    apiKeyStatusDesc: "إذا كنت تواجه مشاكل مع ميزات الذكاء الاصطناعي، استخدم هذا الفحص للتحقق مما إذا كان مفتاح API الخاص بك مهيأً بشكل صحيح ومتصل بخدمات Google.",
    checkApiKey: "فحص المفتاح",
    checkingApiKey: "جاري الفحص...",
    apiKeyStatusOK: "نجاح: مفتاح API صالح ومتصل.",
    apiKeyStatusInvalid: "فشل: مفتاح API غير صالح. يرجى التحقق مرة أخرى من القيمة في متغيرات بيئة Netlify الخاصة بك.",
    apiKeyStatusNotSet: "فشل: مفتاح API غير مهيأ. يرجى إضافة متغير بيئة `API_KEY` في Netlify.",
    wasThisHelpful: "هل كان هذا مفيداً؟",
    yes: "نعم",
    no: "لا",
    feedbackThanks: "شكراً لملاحظاتك!",
    contactPerson: "الشخص المسؤول",
    applicationEmail: "البريد الإلكتروني للتقديم",
    companyDescription: "وصف الشركة",
    notAvailable: "غير متوفر",
    reviews: "تقييمات",
    leaveReview: "اترك تقييمًا",
    rating: "التقييم",
    reviewText: "تقييمك",
    submitReview: "إرسال التقييم",
    noReviewsYet: "لا توجد تقييمات بعد. كن أول من يقيّم!",
    anonymous: "مجهول",
    ratingAndReviewRequired: "التقييم ونص التقييم مطلوبان.",
    emailSummaryIntro: "إليك ملخص لمساراتك المهنية الموصى بها. لعرض التقرير الكامل مع تحليلك الشخصي، يرجى زيارة الموقع أو فتح التقرير المحفوظ.",
    jobOutlookLabel: "الآفاق الوظيفية",
    salaryRangeLabel: "الراتب بعد التدريب",
    registrationUnavailableTitle: "التسجيل غير متاح حالياً",
    registrationUnavailableDesc: "نعتذر، التسجيل العام مغلق في الوقت الحالي. يرجى التواصل مع إدارة الموقع لإنشاء حساب.",
    backToLogin: "العودة لتسجيل الدخول",
    // Resume Builder Translations
    resumeTitle: "منشئ السيرة الذاتية",
    resumeDesc: "أكمل البيانات التالية لإنشاء سيرة ذاتية احترافية.",
    resumePersonalInfo: "المعلومات الشخصية",
    resumeExperience: "الخبرة العملية",
    resumeEducation: "التعليم",
    resumeSkills: "المهارات واللغات",
    resumeGenerateBtn: "إنشاء السيرة الذاتية",
    resumeDownloadPDF: "حفظ كـ PDF",
    resumeDownloadWord: "تحميل كـ Word",
    resumeEdit: "تعديل المعلومات",
    resumeFullName: "الاسم الكامل",
    resumeJobTitle: "المسمى الوظيفي (مثل: مطور ويب)",
    resumeEmail: "البريد الإلكتروني",
    resumePhone: "رقم الهاتف",
    resumeAddress: "العنوان (المدينة، الدولة)",
    resumeSummary: "ملخص مهني (نبذة عنك)",
    resumeAddExperience: "إضافة خبرة",
    resumeAddEducation: "إضافة تعليم",
    resumeCompany: "اسم الشركة",
    resumePosition: "المسمى الوظيفي",
    resumeDateStart: "تاريخ البدء",
    resumeDateEnd: "تاريخ الانتهاء",
    resumeDescription: "وصف المهام",
    resumeSchool: "اسم المدرسة / الجامعة",
    resumeDegree: "الشهادة / الدرجة العلمية",
    resumeSkillsPlaceholder: "مثال: إدارة الوقت، برمجة، لغة إنجليزية...",
    resumePhoto: "صورة شخصية",
    resumePhotoUpload: "رفع صورة",
    remove: "إزالة",
    optimizeResume: "تحسين باستخدام الذكاء الاصطناعي",
    optimizing: "جاري التحسين...",
    resumeOptimizationSuccess: "تم تحسين محتوى السيرة الذاتية بنجاح!",
    resumeOptimizationError: "حدث خطأ أثناء تحسين السيرة الذاتية.",
    resumeGenerateAIPhoto: "توليد صورة بالذكاء الاصطناعي",
    resumeAIPhotoPrompt: "وصف الصورة الشخصية (مثال: محترف يرتدي بدلة)",
    generate: "توليد",
    resumeSelectTemplate: "اختر تصميم السيرة الذاتية",
    templateModern: "عصري",
    templateClassic: "كلاسيكي",
    templateCreative: "إبداعي",
    enhancePhoto: "تحسين الصورة بالذكاء الاصطناعي",
  },
  de: {
    langName: `${germanFlagImg} Deutsch`,
    dir: "ltr",
    headerTitle: "Berufsberatung mit Ahmad Mrashaha",
    footerText: "© 2025 - Entwickelt von Ahmad Mrashaha, um Ihnen zu helfen, Ihren Weg zu finden.",
    welcomeTitle: "Entdecken Sie Ihren idealen Karriereweg in Deutschland",
    welcomeDesc: "Beantworten Sie 30 präzise Fragen zu Ihrer Persönlichkeit, Ihren Fähigkeiten und Ambitionen. Unsere KI wird Ihre Antworten tiefgehend analysieren, um Ihnen die besten Karrierewege, Ausbildungen oder Studiengänge vorzuschlagen.",
    startQuiz: "Persönlichkeitstest starten",
    startQuizDesc: "Beantworten Sie unsere maßgeschneiderten Fragen und erhalten Sie eine persönliche Analyse Ihres Karrierewegs.",
    browseProfessions: "Berufe durchsuchen",
    browseProfessionsDesc: "Erkunden Sie unsere umfangreiche Datenbank mit Berufen, Ausbildungen und Studiengängen.",
    searchAvailableJobs: "Verfügbare Stellen suchen",
    searchAvailableJobsDesc: "Finden Sie jetzt echte, verfügbare Stellenangebote in ganz Deutschland.",
    searchForPraktikum: "Praktikum suchen",
    searchForPraktikumDesc: "Finden Sie Praktikumsplätze und erstellen Sie professionelle Anfrage-E-Mails.",
    createResume: "Lebenslauf (CV) erstellen",
    createResumeDesc: "Beantworten Sie einige Fragen und wir erstellen einen professionellen Lebenslauf für Sie.",
    professionsDesc: "Suchen und durchsuchen Sie Hunderte von Stellenangeboten, Ausbildungen und Studiengängen in Deutschland.",
    quizIntroTitle: "Bevor Sie beginnen",
    quizIntroDesc: "Dieses Quiz besteht aus 30 Fragen zu Ihrer Persönlichkeit, Ihren Fähigkeiten und Ihren Zielen. Ihre ehrlichen Antworten helfen uns, einen detaillierten Bericht mit personalisierten Karrierevorschlägen zu erstellen. Es gibt keine richtigen oder falschen Antworten, seien Sie einfach Sie selbst!",
    quizIntroStartBtn: "Quiz starten",
    back: "Zurück",
    next: "Weiter",
    getResults: "Meine Ergebnisse erhalten",
    loadingTitle: "Analysiere deine Persönlichkeit...",
    loadingDesc: "Unsere KI erstellt Ihren personalisierten Karrierebericht. Dies kann einen Moment dauern.",
    resultsTitleFor: "Ihr Karrierebericht für {name}",
    you: "Sie",
    personalitySummary: "Analyse Ihrer beruflichen Persönlichkeit",
    recommendedPaths: "Empfohlene Karrierewege",
    careerAdvice: "Personalisierte Karrieretipps",
    restart: "Zur Startseite",
    searchPlaceholder: "Suche nach einem Beruf...",
    all: "Alle",
    ausbildung: "Ausbildung",
    study: "Studium",
    job: "Job",
    duration: "Dauer",
    salary: "Gehalt",
    requirements: "Voraussetzungen",
    duties: "Aufgaben",
    skillsRequired: "Benötigte Fähigkeiten",
    home: "Startseite",
    errorText: "Entschuldigung, beim Erstellen Ihrer Ergebnisse ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
    answerHere: "Geben Sie Ihre Antwort hier ein...",
    page: "Seite",
    printReport: "Bericht drucken",
    emailReport: "Per E-Mail senden",
    saveReport: "Ergebnisse speichern",
    reportSaved: "Gespeichert!",
    emailSubject: "Mein Karrierebericht von Berufsberatung",
    jobSearchDesc: "Nutzen Sie KI, um nach aktuell verfügbaren Jobs oder Ausbildungsplätzen in Deutschland zu suchen. Geben Sie Berufsbezeichnung und Ort ein, um Live-Ergebnisse zu erhalten.",
    jobTitlePlaceholder: "z.B. Softwareentwickler, Pflegefachkraft...",
    locationPlaceholder: "z.B. Berlin, Hamburg...",
    search: "Suchen",
    jobSearchLoading: "Suche nach verfügbaren Stellen...",
    jobSearchSources: "Verfügbare Stellenangebote (Quellen)",
    jobSearchPrompt: "Finde mit Google Search aktuell verfügbare Stellenangebote oder Ausbildungsplätze für '{jobTitle}' in oder bei '{location}', Deutschland. Gib keine Zusammenfassung. Gib nur die originalen Quell-URLs an, die du gefunden hast.",
    noJobsFound: "Keine passenden Stellenangebote gefunden.",
    savedReportsTitle: "Gespeicherte Berichte",
    anonymousReport: "Anonymer Bericht",
    viewDetails: "Details ansehen",
    delete: "Löschen",
    confirmDeleteReport: "Möchten Sie diesen Bericht wirklich löschen?",
    noSavedReports: "Noch keine Berichte gespeichert.",
    adminLogin: "Admin-Login",
    responsibleLogin: "Verantwortlichen-Login",
    username: "Benutzername",
    password: "Passwort",
    login: "Anmelden",
    invalidCredentials: "Ungültiger Benutzername oder Passwort.",
    logout: "Abmelden",
    praktikumDesc: "Suchen Sie ein Praktikum? Geben Sie Ihren Interessenbereich und eine Stadt ein. Die KI findet passende Unternehmen für Sie. Wählen Sie eines aus und erstellen Sie dann einen professionellen E-Mail-Entwurf für Ihre Anfrage.",
    fieldPlaceholder: "z.B. IT, Marketing, Ingenieurwesen...",
    yourNamePlaceholder: "Ihr vollständiger Name",
    praktikumSearchBtn: "Unternehmen suchen",
    praktikumCompanyLoading: "Suche nach Praktikumsplatz...",
    praktikumCompanyResult: "Vorgeschlagene Unternehmen",
    company: "Unternehmen",
    location: "Standort",
    select: "Wählen",
    selected: "Ausgewählt",
    praktikumGenerateEmailTitle: "Anfrage-E-Mail erstellen",
    praktikumGenerateEmailBtn: "E-Mail erstellen",
    praktikumEmailLoading: "Schreibe deine E-Mail...",
    praktikumYourEmail: "Ihr E-Mail-Entwurf",
    copyEmail: "E-Mail kopieren",
    copied: "Kopiert!",
    praktikumSearchError: "Leider konnten wir keine passenden Unternehmen finden. Bitte versuchen Sie es mit anderen Suchbegriffen.",
    praktikumNoCompaniesFound: "Keine passenden Unternehmen für Ihre Suche gefunden. Versuchen Sie, Ihre Suchbegriffe anzupassen.",
    praktikumIntroTitle: "Ihr Weg zum Praktikum",
    praktikumIntroDesc1: "Dieses Tool nutzt KI, um Unternehmen zu finden, die möglicherweise Praktikumsplätze in Ihrem gewünschten Bereich und Ort anbieten.",
    praktikumIntroDesc2: "Nachdem Sie ein Unternehmen ausgewählt haben, helfen wir Ihnen, einen professionellen E-Mail-Entwurf zu erstellen, den Sie zur Anfrage versenden können. Sie selbst senden die endgültige E-Mail.",
    praktikumIntroDisclaimer: "<strong>Wichtiger Hinweis:</strong> Diese Methode ist eine Initiativbewerbung. Das bedeutet, die gefundenen Unternehmen haben möglicherweise keine offenen Praktikumsstellen ausgeschrieben. Unser Ziel ist es, Sie zu befähigen, die Initiative zu ergreifen und professionell Kontakt aufzunehmen, was auf dem deutschen Arbeitsmarkt sehr geschätzt wird. Eine Zusage ist nicht zu 100% garantiert, aber es ist ein exzellenter, proaktiver Schritt.",
    praktikumIntroStartBtn: "Verstanden, Suche starten",
    praktikumSearchPrompt: "ROLLE: Hochpräziser Unternehmens-Ermittler für den deutschen Markt.\n\nAUFGABE: Finde über die Google-Suche 5-7 relevant Unternehmen in oder nahe bei '{location}', die potenziell ein '{internshipType}' im Bereich '{field}' anbieten. Priorisiere offizielle Firmenwebsites gegenüber reinen Verzeichniseinträgen.\n\nKRITISCHE ANWEISUNGEN:\n1.  **ABSOLUTE DATENTREUE**: Erfinde NIEMALS Informationen. Wenn eine Information (z.B. Ansprechpartner, E-Mail) in den Suchergebnissen NICHT EXPLIZIT genannt wird, MUSS der Wert für dieses Feld ein leerer String `\"\"` sein.\n2.  **REINES JSON-FORMAT**: Deine Antwort MUSS ausschließlich ein valides JSON-Array. Kein einleitender Text, keine Kommentare, kein Markdown wie ```json.\n\nJSON-AUSGABESTRUKTUR:\n`[{\"name\": \"Vollständiger offizieller Firmenname\", \"address\": \"Straße, PLZ, Ort\", \"contactPerson\": \"\", \"applicationEmail\": \"\", \"description\": \"Ein kurzer Satz, der die Hauptbranche oder Tätigkeit des Unternehmens beschreibt.\", \"website\": \"Offizielle Website-URL\"}]`",
    praktikumEmailPrompt: "Betreff: Anfrage für ein {internshipType} im Bereich {field}\n\nSehr geehrte Damen und Herren,\n\nmein Name ist {userName} und ich habe großes Interesse an einer beruflichen Zukunft im Bereich {field}. Auf der Suche nach praktischen Erfahrungen bin ich auf Ihr Unternehmen, {companyName}, aufmerksam geworden.\n\nHiermit möchte ich höflich anfragen, ob in Ihrem Unternehmen die Möglichkeit besteht, ein {internshipType} zu absolvieren. Ich bin sehr motiviert, von Experten zu lernen und meine Fähigkeiten in einem professionellen Umfeld einzubringen.\n\nÜber eine positive Rückmeldung und Informationen, an wen ich eine formelle Bewerbung richten kann, würde ich mich sehr freuen.\n\nVielen Dank für Ihre Zeit und Mühe.\n\nMit freundlichen Grüßen\n{userName}",
    internshipTypeLabel: "Art des Praktikums",
    internshipTypePlaceholder: "Art des Praktikums wählen...",
    internshipTypeSchool: "Schülerpraktikum",
    internshipTypeAusbildung: "Praktikum zur Berufsausbildung",
    internshipTypeOrientation: "Praktikum zur Berufsorientierung",
    loading: "Wird geladen...",
    underMaintenanceShort: "Wird gewartet",
    underMaintenanceTitle: "Dieser Bereich wird derzeit gewartet",
    underMaintenanceDesc: "Wir arbeiten derzeit an der Verbesserung dieses Bereichs. Er wird in Kürze verfügbar sein. Nur Administratoren können derzeit darauf zugreifen.",
    systemInstruction: "Sie sind ein erfahrener Karriereberater und Psychologe, spezialisiert auf den deutschen Arbeitsmarkt. Ihre Aufgabe ist es, die Antworten von {name}, {age} Jahre alt, auf 30 Fragen zu analysieren, um einen sehr detaillierten und persönlichen Karrierebericht auf Deutsch zu erstellen. Ihre Analyse muss tiefgründig, ermutigend und praktisch sein. Erstellen Sie basierend auf den Antworten einen detaillierten JSON-bericht, der dem Schema entspricht. Der Bericht muss eine genaue Persönlichkeitsanalyse, 3-4 sehr passende und vielfältige Jobvorschläge (einschließlich Ausbildung und Studium) und umsetzbare Karrieretipps enthalten. Sprechen Sie den Benutzer mit seinem Namen an. Ihr Ton muss professionell und sehr unterstützend sein.",
    promptIntro: "Hier sind meine Daten und Antworten auf den Karriere-Fragebogen:",
    promptInstruction: "Bitte erstellen Sie meine detaillierte Karriereanalyse basierend auf diesen Antworten.",
    schemaPersonality: "Eine tiefgehende und detaillierte Analyse der beruflichen Persönlichkeit, Stärken, Entwicklungsbereiche und des idealen Arbeitsstils des Benutzers, in einem professionellen und ermutigenden Ton auf Deutsch verfasst.",
    schemaJobSuggestions: "Eine Liste von 3-4 sehr passenden Vorschlägen für Jobs, Ausbildungen oder Studiengänge in Deutschland auf Deutsch.",
    schemaTitle: "Der Name des Jobs, der Ausbildung oder des Studiums auf Deutsch.",
    schemaDescription: "Eine detaillierte und überzeugende Erklärung, warum dieser Weg zur Persönlichkeit und den Antworten des Benutzers passt, auf Deutsch.",
    schemaDetails: "Wichtige, praktische Details wie Ausbildungsdauer, Gehaltsaussichten, Sprachanforderungen oder Wachstumschancen in Deutschland. Auf Deutsch.",
    schemaCompanyName: "Der Name des Unternehmens.",
    schemaCompanyAddress: "Die vollständige Adresse des Unternehmens.",
    schemaCompanyContact: "Telefonnummer oder E-Mail-Adresse des Unternehmens.",
    schemaCompanyWebsite: "Die offizielle Webseite des Unternehmens.",
    viewReports: "Berichte anzeigen",
    companyWebsite: "Webseite",
    futureProjectTitle: "Zukünftiges Projekt",
    futureProjectDesc: "Dieser Bereich ist für neue und aufregende Funktionen reserviert.",
    apiKeyNotConfiguredError: "Konfigurationsfehler: API-Schlüssel nicht gefunden. Bitte stellen Sie sicher, dass Sie eine `API_KEY`-Umgebungsvariable in Ihren Bereitstellungseinstellungen hinzugefügt haben.",
    invalidApiKeyError: "Entschuldigung, ein Fehler ist aufgetreten. Es scheint, dass der konfigurierte API-Schlüssel ungültig oder abgelaufen ist. Bitte überprüfen Sie Ihre Umgebungsvariablen in den Bereitstellungseinstellungen.",
    apiKeyStatus: "API-Schlüssel-Status",
    apiKeyStatusDesc: "Wenn Sie Probleme mit den KI-Funktionen haben, verwenden Sie diesen Test, um zu überprüfen, ob Ihr API-Schlüssel korrekt konfiguriert und mit den Google-Diensten verbunden ist.",
    checkApiKey: "Schlüssel prüfen",
    checkingApiKey: "Prüfung läuft...",
    apiKeyStatusOK: "Erfolg: API-Schlüssel ist gültig und verbunden.",
    apiKeyStatusInvalid: "Fehler: API-Schlüssel ist ungültig. Bitte überprüfen Sie den Wert in Ihren Netlify-Umgebungsvariablen.",
    apiKeyStatusNotSet: "Fehler: API-Schlüssel nicht konfiguriert. Bitte fügen Sie die `API_KEY`-Umgebungsvariable in Netlify hinzu.",
    wasThisHelpful: "War das hilfreich?",
    yes: "Ja",
    no: "Nein",
    feedbackThanks: "Danke für dein Feedback!",
    contactPerson: "Ansprechpartner",
    applicationEmail: "Bewerbungs-E-Mail",
    companyDescription: "Firmenbeschreibung",
    notAvailable: "Nicht verfügbar",
    reviews: "Bewertungen",
    leaveReview: "Bewertung abgeben",
    rating: "Bewertung",
    reviewText: "Ihre Bewertung",
    submitReview: "Bewertung absenden",
    noReviewsYet: "Noch keine Bewertungen. Seien Sie der Erste!",
    anonymous: "Anonym",
    ratingAndReviewRequired: "Bewertung und Bewertungstext sind erforderlich.",
    emailSummaryIntro: "Hier ist eine Zusammenfassung Ihrer empfohlenen Karrierewege. Um den vollständigen Bericht mit Ihrer persönlichen Analyse einzusehen, besuchen Sie bitte die Website oder öffnen Sie den gespeicherten Bericht.",
    jobOutlookLabel: "Berufsaussichten",
    salaryRangeLabel: "Gehalt nach Ausbildung",
    registrationUnavailableTitle: "Registrierung nicht verfügbar",
    registrationUnavailableDesc: "Die Registrierung ist derzeit geschlossen. Bitte wenden Sie sich an die Administration, um ein Konto zu erstellen.",
    backToLogin: "Zurück zur Anmeldung",
    // Resume Builder Translations
    resumeTitle: "Lebenslauf-Ersteller",
    resumeDesc: "Füllen Sie die folgenden Daten aus, um einen professionellen Lebenslauf zu erstellen.",
    resumePersonalInfo: "Persönliche Daten",
    resumeExperience: "Berufserfahrung",
    resumeEducation: "Ausbildung",
    resumeSkills: "Fähigkeiten & Sprachen",
    resumeGenerateBtn: "Lebenslauf erstellen",
    resumeDownloadPDF: "Als PDF speichern",
    resumeDownloadWord: "Als Word laden",
    resumeEdit: "Daten bearbeiten",
    resumeFullName: "Vollständiger Name",
    resumeJobTitle: "Berufsbezeichnung (z.B. Webentwickler)",
    resumeEmail: "E-Mail-Adresse",
    resumePhone: "Telefonnummer",
    resumeAddress: "Adresse (Stadt, Land)",
    resumeSummary: "Berufliches Profil (Über mich)",
    resumeAddExperience: "Erfahrung hinzufügen",
    resumeAddEducation: "Ausbildung hinzufügen",
    resumeCompany: "Firmenname",
    resumePosition: "Position",
    resumeDateStart: "Startdatum",
    resumeDateEnd: "Enddatum",
    resumeDescription: "Beschreibung der Aufgaben",
    resumeSchool: "Schule / Universität",
    resumeDegree: "Abschluss / Grad",
    resumeSkillsPlaceholder: "z.B. Zeitmanagement, Programmierung, Englisch...",
    resumePhoto: "Profilbild",
    resumePhotoUpload: "Foto hochladen",
    remove: "Entfernen",
    optimizeResume: "Mit KI optimieren",
    optimizing: "Optimieren...",
    resumeOptimizationSuccess: "Lebenslaufinhalt erfolgreich optimiert!",
    resumeOptimizationError: "Optimierung fehlgeschlagen.",
    resumeGenerateAIPhoto: "KI-Foto generieren",
    resumeAIPhotoPrompt: "Bildbeschreibung (z.B. Profi im Anzug)",
    generate: "Generieren",
    resumeSelectTemplate: "Wählen Sie ein Design",
    templateModern: "Modern",
    templateClassic: "Klassisch",
    templateCreative: "Kreativ",
    enhancePhoto: "Foto mit KI verbessern",
  },
  en: {
    langName: `${britishFlagImg} English`,
    dir: "ltr",
    headerTitle: "Career Guidance with Ahmad Mrashaha",
    footerText: "© 2025 - Developed by Ahmad Mrashaha to help you find your way.",
    welcomeTitle: "Discover Your Ideal Career Path in Germany",
    welcomeDesc: "Answer 30 precise questions about your personality, skills, and ambitions. Our AI will deeply analyze your answers to suggest the best career paths, vocational training (Ausbildung), or university programs for you.",
    startQuiz: "Start Career Quiz",
    startQuizDesc: "Answer our tailor-made questions and get a personal analysis of your career path.",
    browseProfessions: "Browse Professions",
    browseProfessionsDesc: "Explore our database of professions, vocational training, and study paths.",
    searchAvailableJobs: "Search Available Jobs",
    searchAvailableJobsDesc: "Find real, available job opportunities across Germany right now.",
    searchForPraktikum: "Search for Internships (Praktikum)",
    searchForPraktikumDesc: "Find internship opportunities and generate professional inquiry emails.",
    createResume: "Create Resume (CV)",
    createResumeDesc: "Answer a few questions and we will generate a professional resume for you.",
    professionsDesc: "Search and browse job opportunities, vocational training, and university studies in Germany.",
    quizIntroTitle: "Before You Begin",
    quizIntroDesc: "This quiz consists of 30 questions about your personality, skills, and ambitions. Your honest answers will help us create a detailed report with personalized career suggestions. There are no right or wrong answers, just be yourself!",
    quizIntroStartBtn: "Start Quiz",
    back: "Back",
    next: "Next",
    getResults: "Get My Results",
    loadingTitle: "Analyzing your personality...",
    loadingDesc: "Our AI is preparing your detailed career report. This might take a moment.",
    resultsTitleFor: "Your Career Report for {name}",
    you: "You",
    personalitySummary: "Your Professional Personality Analysis",
    recommendedPaths: "Recommended Career Paths",
    careerAdvice: "Personalized Career Advice",
    restart: "Back to Home",
    searchPlaceholder: "Search for a profession...",
    all: "All",
    ausbildung: "Vocational Training",
    study: "Study",
    job: "Job",
    duration: "Duration",
    salary: "Salary",
    requirements: "Requirements",
    duties: "Duties",
    skillsRequired: "Skills Required",
    home: "Home",
    errorText: "Sorry, an error occurred while generating your results. Please try again later.",
    answerHere: "Type your answer here...",
    page: "Page",
    printReport: "Print Report",
    emailReport: "Email Report",
    saveReport: "Save Results",
    reportSaved: "Saved!",
    emailSubject: "My Career Report from Career Guidance",
    jobSearchDesc: "Use AI to search for currently available jobs or vocational training opportunities in Germany. Enter the job title and location to get live results.",
    jobTitlePlaceholder: "e.g., Software Developer, Nurse...",
    locationPlaceholder: "e.g., Berlin, Hamburg...",
    search: "Search",
    jobSearchLoading: "Searching for available jobs...",
    jobSearchSources: "Available Job Openings (Sources)",
    jobSearchPrompt: "Using Google Search, find currently available jobs or vocational training (Ausbildung) opportunities for '{jobTitle}' in or near '{location}', Germany. Do not provide a summary. Only provide the original source links you found.",
    noJobsFound: "No matching job openings found.",
    savedReportsTitle: "Saved Reports",
    anonymousReport: "Anonymous Report",
    viewDetails: "View Details",
    delete: "Delete",
    confirmDeleteReport: "Are you sure you want to delete this report?",
    noSavedReports: "No saved reports yet.",
    adminLogin: "Admin Login",
    responsibleLogin: "Responsible Login",
    username: "Username",
    password: "Password",
    login: "Login",
    invalidCredentials: "Invalid username or password.",
    logout: "Logout",
    praktikumDesc: "Looking for an internship (Praktikum)? Enter your field of interest and a city, and the AI will find suitable companies for you. Select one, then generate a professional email draft to inquire.",
    fieldPlaceholder: "e.g., IT, Marketing, Engineering...",
    yourNamePlaceholder: "Your full name",
    praktikumSearchBtn: "Search for Companies",
    praktikumCompanyLoading: "Searching for internship opportunities...",
    praktikumCompanyResult: "Suggested Companies",
    company: "Company",
    location: "Location",
    select: "Select",
    selected: "Selected",
    praktikumGenerateEmailTitle: "Generate an Inquiry Email",
    praktikumGenerateEmailBtn: "Generate Email",
    praktikumEmailLoading: "Writing your email...",
    praktikumYourEmail: "Your Email Draft",
    copyEmail: "Copy Email",
    copied: "Copied!",
    praktikumSearchError: "Sorry, we could not find suitable companies. Please try different search terms.",
    praktikumNoCompaniesFound: "No matching companies found for your search. Try adjusting your search terms.",
    praktikumIntroTitle: "Your Path to an Internship (Praktikum)",
    praktikumIntroDesc1: "This tool uses AI to find companies that might offer internship opportunities in your desired field and location.",
    praktikumIntroDesc2: "After selecting a company, we will help you generate a professional email draft that you can send to inquire about an opportunity. You will send the final email yourself.",
    praktikumIntroDisclaimer: "<strong>Important Note:</strong> This method is an 'unsolicited application' (Initiativbewerbung). This means the companies we find may not have publicly advertised internship vacancies. Our goal is to empower you to take the initiative and make professional contact, which is highly valued in the German job market. An opportunity is not 100% guaranteed, but it is an excellent, proactive step.",
    praktikumIntroStartBtn: "Understood, Let's Start Searching",
    praktikumSearchPrompt: "ROLE: High-precision company investigator for the German market.\n\nTASK: Using Google Search, find 5-7 relevant companies in or near '{location}' that potentially offer a '{internshipType}' in the '{field}' sector. Prioritize official company websites over simple directory listings.\n\nKRITICAL INSTRUCTIONS:\n1.  **ABSOLUTE DATA FIDELITY**: NEVER invent information. If a piece of information (e.g., contact person, email) is NOT EXPLICITLY mentioned in the search results, the value for that field MUST be an empty string `\"\"`.\n2.  **PURE JSON FORMAT**: Your entire response MUST be exclusively a valid JSON array. No introductory text, no comments, no markdown like ```json.\n\nJSON OUTPUT STRUCTURE:\n`[{\"name\": \"Full Official Company Name\", \"address\": \"Street, Postal Code, City\", \"contactPerson\": \"\", \"applicationEmail\": \"\", \"description\": \"A single, concise sentence describing the company's main industry or activity.\", \"website\": \"Official Website URL\"}]`",
    praktikumEmailPrompt: "You are an excellent career assistant. Write a professional and polite draft email in GERMAN. The email is from '{userName}' to '{companyName}' to inquire about an internship (Praktikum) in the '{field}' field. The purpose of the internship is '{internshipType}'. Adapt the content and tone VERY precisely to match the internship type:\n\n- If the type is 'for school' (Schülerpraktikum): Write as a motivated student. Mention this is a mandatory school internship. Ask about possible time frames and required documents. The tone should be polite and youthful.\n- If the type is 'for career orientation' (Berufsorientierung): Express strong interest in the '{field}' area and the company. Explain that the goal is to gain initial insights and facilitate career choice. The tone should be curious and enthusiastic.\n- If the type is 'for vocational training' (Ausbildung): Write more formally and professionally. State that the applicant is seeking vocational training in this field and wants to gain practical experience. Emphasize the motivation to apply skills practically.\n\nAlways use a proper salutation (Sehr geehrte Damen und Herren,) and closing (Mit freundlichen Grüßen). Ask about the right contact person for applications.",
    internshipTypeLabel: "Type of Internship",
    internshipTypePlaceholder: "Select internship type...",
    internshipTypeSchool: "For School",
    internshipTypeAusbildung: "For Vocational Training",
    internshipTypeOrientation: "For Career Orientation",
    loading: "Loading...",
    underMaintenanceShort: "Under Maintenance",
    underMaintenanceTitle: "This Section is Under Maintenance",
    underMaintenanceDesc: "We are currently working on improving this section and it will be available soon. Only administrators can currently access it.",
    systemInstruction: "You are an expert career advisor and psychologist specializing in the German job market. Your task is to analyze the answers of {name}, age {age}, to 30 questions to create a very detailed and highly personal career report in English. Your analysis must be profound, encouraging, and practical. Based on the answers, create a detailed JSON report that matches the schema. The report must include an accurate personality analysis, 3-4 very suitable and diverse job suggestions (including Ausbildung and university studies), and actionable career advice. Address the user by their name. Your tone must be professional and very supportive.",
    promptIntro: "Here is my data and my answers to the career guidance questionnaire:",
    promptInstruction: "Please provide my detailed career analysis based on these answers.",
    schemaPersonality: "A deep and detailed analysis of the user's professional personality, strengths, areas for development, and ideal work style, written in a professional and encouraging tone in English.",
    schemaJobSuggestions: "A list of 3-4 very suitable suggestions for jobs, vocational training (Ausbildung), or university studies in Germany, in English.",
    schemaTitle: "The name of the job, vocational training, or study program, in English.",
    schemaDescription: "A detailed and convincing explanation of why this path fits the user's personality and answers, in English.",
    schemaDetails: "Key, practical details such as training duration, salary expectations, language requirements, or growth opportunities in Germany. In English.",
    schemaCompanyName: "The name of the company.",
    schemaCompanyAddress: "The full address of the company.",
    schemaCompanyContact: "The company's phone number or email address.",
    schemaCompanyWebsite: "The official website of the company.",
    viewReports: "View Reports",
    companyWebsite: "Website",
    futureProjectTitle: "Future Project",
    futureProjectDesc: "This space is reserved for new and exciting features.",
    apiKeyNotConfiguredError: "Configuration Error: API key not found. Please ensure you have added an `API_KEY` environment variable in your deployment settings.",
    invalidApiKeyError: "Sorry, an error occurred. It seems the configured API key is invalid or has expired. Please check your environment variables in your deployment settings.",
    apiKeyStatus: "API Key Status",
    apiKeyStatusDesc: "If you are experiencing issues with the AI features, use this checker to verify if your API key is correctly configured and connected to Google's services.",
    checkApiKey: "Check Key",
    checkingApiKey: "Checking...",
    apiKeyStatusOK: "Success: API key is valid and connected.",
    apiKeyStatusInvalid: "Failure: API key is invalid. Please double-check the value in your Netlify environment variables.",
    apiKeyStatusNotSet: "Failure: API key is not configured. Please add the `API_KEY` environment variable in Netlify.",
    wasThisHelpful: "Was this helpful?",
    yes: "Yes",
    no: "No",
    feedbackThanks: "Thanks for your feedback!",
    contactPerson: "Contact Person",
    applicationEmail: "Application Email",
    companyDescription: "Company Description",
    notAvailable: "Not available",
    reviews: "Reviews",
    leaveReview: "Leave a Review",
    rating: "Rating",
    reviewText: "Your Review",
    submitReview: "Submit Review",
    noReviewsYet: "No reviews yet. Be the first!",
    anonymous: "Anonymous",
    ratingAndReviewRequired: "Rating and review text are required.",
    emailSummaryIntro: "Here is a summary of your recommended career paths. To view the full report with your personal analysis, please visit the website or open the saved report.",
    jobOutlookLabel: "Job Outlook",
    salaryRangeLabel: "Salary (Post-Training)",
    registrationUnavailableTitle: "Registration Unavailable",
    registrationUnavailableDesc: "Registration is currently closed. Please contact site administration to create an account.",
    backToLogin: "Back to Login",
    // Resume Builder Translations
    resumeTitle: "Resume Builder",
    resumeDesc: "Complete the following data to create a professional resume.",
    resumePersonalInfo: "Personal Information",
    resumeExperience: "Work Experience",
    resumeEducation: "Education",
    resumeSkills: "Skills & Languages",
    resumeGenerateBtn: "Generate Resume",
    resumeDownloadPDF: "Save as PDF",
    resumeDownloadWord: "Download as Word",
    resumeEdit: "Edit Data",
    resumeFullName: "Full Name",
    resumeJobTitle: "Job Title (e.g. Web Developer)",
    resumeEmail: "Email Address",
    resumePhone: "Phone Number",
    resumeAddress: "Address (City, Country)",
    resumeSummary: "Professional Summary (About Me)",
    resumeAddExperience: "Add Experience",
    resumeAddEducation: "Add Education",
    resumeCompany: "Company Name",
    resumePosition: "Position",
    resumeDateStart: "Start Date",
    resumeDateEnd: "End Date",
    resumeDescription: "Description of Tasks",
    resumeSchool: "School / University",
    resumeDegree: "Degree / Certificate",
    resumeSkillsPlaceholder: "e.g., Time Management, Programming, English...",
    resumePhoto: "Profile Photo",
    resumePhotoUpload: "Upload Photo",
    remove: "Remove",
    optimizeResume: "Optimize with AI",
    optimizing: "Optimizing...",
    resumeOptimizationSuccess: "Resume content optimized successfully!",
    resumeOptimizationError: "Failed to optimize resume.",
    resumeGenerateAIPhoto: "Generate AI Photo",
    resumeAIPhotoPrompt: "Image description (e.g. professional in a suit)",
    generate: "Generate",
    resumeSelectTemplate: "Select Resume Design",
    templateModern: "Modern",
    templateClassic: "Classic",
    templateCreative: "Creative",
    enhancePhoto: "Enhance Photo with AI",
  },
  tr: {
    langName: `${turkishFlagImg} Türkçe`,
    dir: "ltr",
    headerTitle: "Ahmad Mrashaha ile Kariyer Rehberliği",
    footerText: "© 2025 - Yolunuzu bulmanıza yardımcı olmak için Ahmad Mrashaha tarafından geliştirildi.",
    welcomeTitle: "Almanya'daki İdeal Kariyer Yolunuzu Keşfedin",
    welcomeDesc: "Kişiliğiniz, becerileriniz ve hedefleriniz hakkında 30 hassas soruyu yanıtlayın. Yapay zekamız, size en iyi kariyer yollarını, mesleki eğitimi (Ausbildung) veya üniversite programlarını önermek için cevaplarınızı derinlemesine analiz edecektir.",
    startQuiz: "Kişilik Testine Başla",
    startQuizDesc: "Size özel hazırlanmış sorularımızı yanıtlayın ve kariyer yolunuzun kişisel bir analizini alın.",
    browseProfessions: "Mesleklere Göz At",
    browseProfessionsDesc: "Geniş meslek, mesleki eğitim ve üniversite programları veritabanımızı keşfedin.",
    searchAvailableJobs: "Mevcut İşleri Ara",
    searchAvailableJobsDesc: "Almanya genelinde şu anda mevcut olan gerçek iş fırsatlarını bulun.",
    searchForPraktikum: "Staj Ara (Praktikum)",
    searchForPraktikumDesc: "Staj yerleri bulun ve profesyonel başvuru e-postaları oluşturun.",
    createResume: "Özgeçmiş (CV) Oluştur",
    createResumeDesc: "Birkaç soruyu yanıtlayın ve sizin için profesyonel bir özgeçmiş oluşturalım.",
    professionsDesc: "Almanya'daki yüzlerce iş, mesleki eğitim ve üniversite fırsatını arayın ve inceleyin.",
    quizIntroTitle: "Başlamadan Önce",
    quizIntroDesc: "Bu test, kişiliğiniz, becerileriniz ve hedefleriniz hakkında 30 sorudan oluşmaktadır. Dürüst cevaplarınız, kişiselleştirilmiş kariyer önerileri içeren ayrıntılı bir rapor oluşturmamıza yardımcı olacaktır. Doğru ya da yanlış cevap yoktur, sadece kendiniz olun!",
    quizIntroStartBtn: "Teste Başla",
    back: "Geri",
    next: "İleri",
    getResults: "Sonuçlarımı Al",
    loadingTitle: "Kişiliğiniz analiz ediliyor...",
    loadingDesc: "Yapay zeka kişiselleştirilmiş kariyer raporunuzu hazırlıyor. Bu birkaç dakika sürebilir.",
    resultsTitleFor: "{name} için Kariyer Raporun",
    you: "Sizin",
    personalitySummary: "Profesyonel Kişilik Analiziniz",
    recommendedPaths: "Önerilen Kariyer Yolları",
    careerAdvice: "Kişiselleştirilmiş Kariyer Tavsiyeleri",
    restart: "Ana Sayfaya Dön",
    searchPlaceholder: "Bir meslek arayın...",
    all: "Tümü",
    ausbildung: "Mesleki Eğitim",
    study: "Üniversite",
    job: "İş",
    duration: "Süre",
    salary: "Maaş",
    requirements: "Gereksinimler",
    duties: "Görevler",
    skillsRequired: "Gerekli Beceriler",
    home: "Ana Sayfa",
    errorText: "Üzgünüz, sonuçlarınız oluşturulurken bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
    answerHere: "Cevabınızı buraya yazın...",
    page: "Sayfa",
    printReport: "Raporu Yazdır",
    emailReport: "E-posta ile Gönder",
    saveReport: "Sonuçları Kaydet",
    reportSaved: "Kaydedildi!",
    emailSubject: "Kariyer Rehberliği'nden Kariyer Raporum",
    jobSearchDesc: "Almanya'da mevcut işleri veya mesleki eğitim fırsatlarını aramak için yapay zekayı kullanın. Canlı sonuçlar almak için iş unvanını ve konumu girin.",
    jobTitlePlaceholder: "Örn: Yazılım Geliştirici, Hemşire...",
    locationPlaceholder: "Örn: Berlin, Hamburg...",
    search: "Ara",
    jobSearchLoading: "Mevcut işler aranıyor...",
    jobSearchSources: "Mevcut İş İlanları (Kaynaklar)",
    jobSearchPrompt: "Google Arama'yı kullanarak, Almanya'da '{location}' veya yakınında '{jobTitle}' için mevcut iş veya mesleki eğitim (Ausbildung) ilanlarını bulun. Bir özet sunmayın. Sadece bulduğunuz orijinal kaynak URL'lerini sağlayın.",
    noJobsFound: "Uygun iş ilanı bulunamadı.",
    savedReportsTitle: "Kayıtlı Raporlar",
    anonymousReport: "İsimsiz Rapor",
    viewDetails: "Detayları Görüntüle",
    delete: "Sil",
    confirmDeleteReport: "Bu raporu silmek istediğinizden emin misiniz?",
    noSavedReports: "Henüz kayıtlı rapor yok.",
    adminLogin: "Yönetici Girişi",
    responsibleLogin: "Sorumlu Girişi",
    username: "Kullanıcı Adı",
    password: "Şifre",
    login: "Giriş Yap",
    invalidCredentials: "Geçersiz kullanıcı adı veya şifre.",
    logout: "Çıkış Yap",
    praktikumDesc: "Staj mı arıyorsunuz? İlgilendiğiniz alanı ve bir şehri girin. Yapay zeka sizin için uygun şirketleri bulacaktır. Birini seçin ve ardından profesyonel bir başvuru e-postası taslağı oluşturun.",
    fieldPlaceholder: "Örn: Bilişim, Pazarlama, Mühendislik...",
    yourNamePlaceholder: "Tam adınız",
    praktikumSearchBtn: "Şirketleri Ara",
    praktikumCompanyLoading: "Staj fırsatları aranıyor...",
    praktikumCompanyResult: "Önerilen Şirketler",
    company: "Şirket",
    location: "Konum",
    select: "Seç",
    selected: "Seçildi",
    praktikumGenerateEmailTitle: "Soru E-postası Oluştur",
    praktikumGenerateEmailBtn: "E-posta Oluştur",
    praktikumEmailLoading: "E-postanız yazılıyor...",
    praktikumYourEmail: "E-posta Taslağınız",
    copyEmail: "E-postayı Kopyala",
    copied: "Kopyalandı!",
    praktikumSearchError: "Üzgünüz, uygun şirket bulamadık. Lütfen farklı arama terimleri deneyin.",
    praktikumNoCompaniesFound: "Aramanızla eşleşen şirket bulunamadı. Arama terimlerinizi değiştirmeyi deneyin.",
    praktikumIntroTitle: "Staj Yolunuz (Praktikum)",
    praktikumIntroDesc1: "Bu araç, istediğiniz alanda ve konumda staj imkanı sunabilecek şirketleri bulmak için yapay zekayı kullanır.",
    praktikumIntroDesc2: "Bir şirket seçtikten sonra, başvuru yapmak için gönderebileceğiniz profesyonel bir e-posta taslağı oluşturmanıza yardımcı olacağız. Son e-postayı kendiniz göndereceksiniz.",
    praktikumIntroDisclaimer: "<strong>Önemli Not:</strong> Bu yöntem bir 'talep dışı başvuru' (Initiativbewerbung). Bu, bulduğumuz şirketlerin halka açık stajyer ilanları olmayabileceği anlamına gelir. Amacımız, Alman iş piyasasında çok değer verilen inisiyatif almanızı ve profesyonel iletişim kurmanızı sağlamaktır. Bir fırsat %100 garanti edilmez, ancak bu mükemmel ve proaktif bir adımdır.",
    praktikumIntroStartBtn: "Anlaşıldı, Aramaya Başlayalım",
    praktikumSearchPrompt: "ROL: Alman pazarı için yüksek hassasiyetli şirket araştırmacısı.\n\nGÖREV: Google Arama'yı kullanarak '{location}' veya yakınlarında, '{field}' sektöründe potansiyel olarak bir '{internshipType}' sunan 5-7 ilgili şirket bulun. Basit dizin listelemeleri yerine resmi şirket web sitelerine öncelik verin.\n\nKRİTİK TALİMATLAR:\n1.  **MUTLAK VERİ DOĞRULUĞU**: ASLA bilgi uydurmayın. Bir bilgi (örneğin, iletişim kişisi, e-posta) arama sonuçlarında AÇIKÇA belirtilmemişse, o alanın değeri MUTLAKA boş bir dize `\"\"` olmalıdır.\n2.  **SAF JSON FORMATI**: Tüm yanıtınız SADECE geçerli bir JSON dizisi olmalıdır. Giriş metni, yorum veya ```json gibi markdown içermemelidir.\n\nJSON ÇIKTI YAPISI:\n`[{\"name\": \"Tam Resmi Şirket Adı\", \"address\": \"Sokak, Posta Kodu, Şehir\", \"contactPerson\": \"\", \"applicationEmail\": \"\", \"description\": \"Şirketin ana endüstrisini veya faaliyetini tanımlayan tek ve öz bir cümle.\", \"website\": \"Resmi Web Sitesi URL'si\"}]`",
    praktikumEmailPrompt: "Harika bir kariyer asistanısın. ALMANCA dilinde profesyonel ve kibar bir e-posta taslağı yaz. E-posta, '{userName}' tarafından '{companyName}' şirketine '{field}' alanında bir staj (Praktikum) hakkında bilgi almak için yazılmıştır. Stajın amacı '{internshipType}'. İçeriği ve tonu, staj türüne ÇOK hassas bir şekilde uyarlayın:\n\n- Tür 'okul için' (Schülerpraktikum) ise: Motive bir öğrenci olarak yazın. Bunun zorunlu bir okul stajı olduğunu belirtin. Olası zaman dilimlerini ve gerekli belgeleri sorun. Ton kibar ve genç olmalıdır.\n- Tür 'kariyer yönelimi için' (Berufsorientierung) ise: '{field}' alanına ve şirkete güçlü bir ilgi ifade edin. Amacın ilk izlenimleri kazanmak ve kariyer seçimini kolaylaştırmak olduğunu açıklayın. Ton meraklı ve hevesli olmalıdır.\n- Tür 'mesleki eğitim için' (Ausbildung) ise: Daha resmi ve profesyonel bir şekilde yazın. Başvuranın bu alanda mesleki eğitim aradığını ve pratik deneyim kazanmak istediğini belirtin. Becerileri pratik olarak uygulama motivasyonunu vurgulayın.\n\nHer zaman uygun bir selamlama (Sehr geehrte Damen und Herren,) ve kapanış (Mit freundlichen Grüßen). Başvurular için doğru iletişim kişisini sorun.",
    internshipTypeLabel: "Staj Türü",
    internshipTypePlaceholder: "Staj türünü seçin...",
    internshipTypeSchool: "Okul İçin",
    internshipTypeAusbildung: "Mesleki Eğitim İçin",
    internshipTypeOrientation: "Kariyer Yönelimi İçin",
    loading: "Yükleniyor...",
    underMaintenanceShort: "Bakımda",
    underMaintenanceTitle: "Bu Bölüm Bakımda",
    underMaintenanceDesc: "Şu anda bu bölümü geliştirmek için çalışıyoruz ve yakında kullanıma sunulacak. Şu anda sadece yöneticiler erişebilir.",
    systemInstruction: "Alman iş piyasasında uzmanlaşmış bir uzman kariyer danışmanı ve psikologsunuz. Göreviniz, {name}, yaş {age}, tarafından 30 soruya verilen cevapları analiz ederek Türkçe dilinde çok detaylı ve son derece kişisel bir kariyer raporu oluşturmaktır. Analiziniz derin, teşvik edici ve pratik olmalıdır. Cevaplara dayanarak, şemaya uygun detaylı bir JSON raporu oluşturun. Rapor, doğru bir kişilik analizi, 3-4 çok uygun ve çeşitli iş önerisi (Ausbildung ve üniversite dahil) ve uygulanabilir kariyer tavsiyeleri içermelidir. Kullanıcıya adıyla hitap edin. Tonunuz profesyonel ve çok destekleyici olmalıdır.",
    promptIntro: "İşte kariyer rehberliği anketine verdiğim verilerim ve cevaplarım:",
    promptInstruction: "Lütfen bu cevaplara dayanarak detaylı kariyer analizimi sağlayın.",
    schemaPersonality: "Kullanıcının profesyonel kişiliğinin, güçlü yönlerinin, gelişim alanlarının ve ideal çalışma tarzının, profesyonel ve teşvik edici bir tonda Türkçe olarak yazılmış derin ve detaylı bir analizi.",
    schemaJobSuggestions: "Almanya'da işler, mesleki eğitim (Ausbildung) veya üniversite çalışmaları için çok uygun 3-4 öneriden oluşan bir liste, Türkçe.",
    schemaTitle: "İşin, mesleki eğitimin veya üniversite programının adı, Türkçe.",
    schemaDescription: "Bu yolun neden kullanıcının kişiliğine ve cevaplarına uyduğunun detaylı ve ikna edici bir açıklaması, Türkçe.",
    schemaDetails: "Eğitim süresi, maaş beklentileri, dil gereksinimleri veya Almanya'daki büyüme fırsatları gibi önemli, pratik detaylar. Türkçe.",
    schemaCompanyName: "Şirketin adı.",
    schemaCompanyAddress: "Şirketin tam adresi.",
    schemaCompanyContact: "Şirketin telefon numarası veya e-posta adresi.",
    schemaCompanyWebsite: "Şirketin resmi web sitesi.",
    viewReports: "Raporları Görüntüle",
    companyWebsite: "Web Sitesi",
    futureProjectTitle: "Gelecek Proje",
    futureProjectDesc: "Bu alan yeni ve heyecan verici özellikler için ayrılmıştır.",
    apiKeyNotConfiguredError: "Yapılandırma Hatası: API anahtarı bulunamadı. Lütfen dağıtım ayarlarınıza bir `API_KEY` ortam değişkeni eklediğinizden emin olun.",
    invalidApiKeyError: "Üzgünüz, bir hata oluştu. Yapılandırılmış API anahtarının geçersiz veya süresi dolmuş gibi görünüyor. Lütfen dağıtım ayarlarınızdaki ortam değişkenlerinizi kontrol edin.",
    apiKeyStatus: "API Anahtarı Durumu",
    apiKeyStatusDesc: "Yapay zeka özellikleriyle ilgili sorunlar yaşıyorsanız, API anahtarınızın doğru yapılandırılıp yapılandırılmadığını ve Google'ın hizmetlerine bağlı olup olmadığını doğrulamak için bu denetleyiciyi kullanın.",
    checkApiKey: "Anahtarı Kontrol Et",
    checkingApiKey: "Kontrol ediliyor...",
    apiKeyStatusOK: "Başarılı: API anahtarı geçerli ve bağlı.",
    apiKeyStatusInvalid: "Başarısız: API anahtarı geçersiz. Lütfen Netlify ortam değişkenlerinizdeki değeri tekrar kontrol edin.",
    apiKeyStatusNotSet: "Başarısız: API anahtarı yapılandırılmamış. Lütfen Netlify'da `API_KEY` ortam değişkenini ekleyin.",
    wasThisHelpful: "Bu yardımcı oldu mu?",
    yes: "Evet",
    no: "Hayır",
    feedbackThanks: "Geri bildiriminiz için teşekkürler!",
    contactPerson: "İlgili Kişi",
    applicationEmail: "Başvuru E-postası",
    companyDescription: "Şirket Açıklaması",
    notAvailable: "Mevcut değil",
    reviews: "Yorumlar",
    leaveReview: "Yorum Bırak",
    rating: "Değerlendirme",
    reviewText: "Yorumunuz",
    submitReview: "Yorumu Gönder",
    noReviewsYet: "Henüz yorum yok. İlk siz olun!",
    anonymous: "Anonim",
    ratingAndReviewRequired: "Değerlendirme ve yorum metni gereklidir.",
    emailSummaryIntro: "İşte önerilen kariyer yollarınızın bir özeti. Kişisel analizinizle tam raporu görüntülemek için lütfen web sitesini ziyaret edin veya kaydedilen raporu açın.",
    jobOutlookLabel: "İş Görünümü",
    salaryRangeLabel: "Maaş (Eğitim Sonrası)",
    registrationUnavailableTitle: "Kayıt Mevcut Değil",
    registrationUnavailableDesc: "Kayıt şu anda kapalıdır. Hesap oluşturmak için lütfen site yönetimiyle iletişime geçin.",
    backToLogin: "Girişe Dön",
    // Resume Builder Translations
    resumeTitle: "Özgeçmiş Oluşturucu",
    resumeDesc: "Profesyonel bir özgeçmiş oluşturmak için aşağıdaki verileri doldurun.",
    resumePersonalInfo: "Kişisel Bilgiler",
    resumeExperience: "İş Deneyimi",
    resumeEducation: "Eğitim",
    resumeSkills: "Beceriler & Diller",
    resumeGenerateBtn: "Özgeçmiş Oluştur",
    resumeDownloadPDF: "PDF Olarak Kaydet",
    resumeDownloadWord: "Word Olarak İndir",
    resumeEdit: "Verileri Düzenle",
    resumeFullName: "Ad Soyad",
    resumeJobTitle: "İş Unvanı (Örn: Web Geliştirici)",
    resumeEmail: "E-posta Adresi",
    resumePhone: "Telefon Numarası",
    resumeAddress: "Adres (Şehir, Ülke)",
    resumeSummary: "Özet (Hakkımda)",
    resumeAddExperience: "Deneyim Ekle",
    resumeAddEducation: "Eğitim Ekle",
    resumeCompany: "Şirket Adı",
    resumePosition: "Pozisyon",
    resumeDateStart: "Başlangıç Tarihi",
    resumeDateEnd: "Bitiş Tarihi",
    resumeDescription: "Görev Tanımı",
    resumeSchool: "Okul / Üniversite",
    resumeDegree: "Derece / Sertifika",
    resumeSkillsPlaceholder: "Örn: Zaman Yönetimi, Programlama, İngilizce...",
    resumePhoto: "Profil Fotoğrafı",
    resumePhotoUpload: "Fotoğraf Yükle",
    remove: "Kaldır",
    optimizeResume: "Yapay Zeka ile Optimize Et",
    optimizing: "Optimize ediliyor...",
    resumeOptimizationSuccess: "Özgeçmiş içeriği başarıyla optimize edildi!",
    resumeOptimizationError: "Özgeçmiş optimize edilemedi.",
    resumeGenerateAIPhoto: "Yapay Zeka Fotoğrafı Oluştur",
    resumeAIPhotoPrompt: "Görüntü açıklaması (örn. takım elbiseli profesyonel)",
    generate: "Oluştur",
    resumeSelectTemplate: "Özgeçmiş Tasarımı Seç",
    templateModern: "Modern",
    templateClassic: "Klasik",
    templateCreative: "Yaratıcı",
    enhancePhoto: "Fotoğrafı YZ ile Geliştir",
  }
};

export const quizQuestions = {
  ar: [
    { id: 'name', type: 'text', question: 'ما هو اسمك الكامل؟' },
    { id: 'age', type: 'number', question: 'كم عمرك؟' },
    { id: 'work_style', type: 'choice', question: 'كيف تفضل العمل؟', options: ['في فريق', 'بشكل مستقل', 'مختلط'] },
    { id: 'environment', type: 'choice', question: 'ما هي بيئة العمل المفضلة لديك؟', options: ['مكتب', 'خارج المكتب', 'عن بعد', 'ورشة عمل'] },
    { id: 'problem_solving', type: 'choice', question: 'كيف تتعامل مع المشكلات؟', options: ['بشكل تحليلي', 'بشكل إبداعي', 'بشكل عملي'] }
  ],
  de: [
    { id: 'name', type: 'text', question: 'Wie ist Ihr vollständiger Name?' },
    { id: 'age', type: 'number', question: 'Wie alt sind Sie?' },
    { id: 'work_style', type: 'choice', question: 'Wie arbeiten Sie am liebsten?', options: ['Im Team', 'Unabhängig', 'Gemischt'] },
    { id: 'environment', type: 'choice', question: 'Welche Arbeitsumgebung bevorzugen Sie?', options: ['Büro', 'Draußen', 'Remote', 'Werkstatt'] },
    { id: 'problem_solving', type: 'choice', question: 'Wie gehen Sie Probleme an?', options: ['Analytisch', 'Kreativ', 'Praktisch'] }
  ],
  en: [
    { id: 'name', type: 'text', question: 'What is your full name?' },
    { id: 'age', type: 'number', question: 'How old are you?' },
    { id: 'work_style', type: 'choice', question: 'How do you prefer to work?', options: ['In a team', 'Independently', 'Mixed'] },
    { id: 'environment', type: 'choice', question: 'What is your preferred work environment?', options: ['Office', 'Outdoors', 'Remote', 'Workshop'] },
    { id: 'problem_solving', type: 'choice', question: 'How do you approach problems?', options: ['Analytically', 'Creatively', 'Practically'] }
  ],
  tr: [
    { id: 'name', type: 'text', question: 'Tam adınız nedir?' },
    { id: 'age', type: 'number', question: 'Kaç yaşındasınız?' },
    { id: 'work_style', type: 'choice', question: 'Nasıl çalışmayı tercih edersiniz?', options: ['Takım halinde', 'Bağımsız', 'Karışık'] },
    { id: 'environment', type: 'choice', question: 'Tercih ettiğiniz çalışma ortamı nedir?', options: ['Ofis', 'Dışarıda', 'Uzaktan', 'Atölye'] },
    { id: 'problem_solving', type: 'choice', question: 'Sorunlara nasıl yaklaşırsınız?', options: ['Analitik', 'Yaratıcı', 'Pratik'] }
  ]
};

export const professions = [
  {
    title: { ar: 'مطور برمجيات', de: 'Softwareentwickler', en: 'Software Developer', tr: 'Yazılım Geliştirici' },
    duration: { ar: '3 سنوات (Ausbildung) أو درجة جامعية', de: '3 Jahre (Ausbildung) oder Studium', en: '3 years (Ausbildung) or University Degree', tr: '3 Yıl (Ausbildung) veya Üniversite Derecesi' },
    salary: { ar: '45,000 يورو - 70,000 يورو سنوياً', de: '45.000 € - 70.000 € pro Jahr', en: '€45,000 - €70,000 per year', tr: 'Yılda 45.000 € - 70.000 €' },
    salaryRange: { ar: 'متوسط إلى مرتفع', de: 'Mittel bis Hoch', en: 'Medium to High', tr: 'Orta - Yüksek' },
    jobOutlook: { ar: 'طلب مرتفع جداً', de: 'Sehr hohe Nachfrage', en: 'Very High Demand', tr: 'Çok Yüksek Talep' },
    requirements: { ar: 'مهارات منطقية، معرفة بالبرمجة، لغة إنجليزية جيدة', de: 'Logisches Denken, Programmierkenntnisse, gutes Englisch', en: 'Logical thinking, programming skills, good English', tr: 'Mantıksal düşünme, programlama becerileri, iyi İngilizce' },
    duties: { ar: 'تطوير التطبيقات، صيانة الأنظمة، حل المشكلات التقنية', de: 'Apps entwickeln, Systeme warten, technische Probleme lösen', en: 'Developing apps, maintaining systems, solving technical problems', tr: 'Uygulama geliştirme, sistem bakımı, teknik sorunları çözme' },
    skillsRequired: { ar: 'Java, Python, JavaScript, SQL', de: 'Java, Python, JavaScript, SQL', en: 'Java, Python, JavaScript, SQL', tr: 'Java, Python, JavaScript, SQL' }
  },
  {
    title: { ar: 'ممرض / ممرضة', de: 'Pflegefachkraft', en: 'Nurse', tr: 'Hemşire' },
    duration: { ar: '3 سنوات (Ausbildung)', de: '3 Jahre (Ausbildung)', en: '3 years (Ausbildung)', tr: '3 Yıl (Ausbildung)' },
    salary: { ar: '35,000 يورو - 45,000 يورو سنوياً', de: '35.000 € - 45.000 € pro Jahr', en: '€35,000 - €45,000 per year', tr: 'Yılda 35.000 € - 45.000 €' },
    salaryRange: { ar: 'متوسط', de: 'Mittel', en: 'Medium', tr: 'Orta' },
    jobOutlook: { ar: 'طلب مرتفع للغاية', de: 'Extrem hohe Nachfrage', en: 'Extremely High Demand', tr: 'Son Derece Yüksek Talep' },
    requirements: { ar: 'تعاطف، قدرة على تحمل الضغط، لغة ألمانية جيدة (B2)', de: 'Empathie, Belastbarkeit, gutes Deutsch (B2)', en: 'Empathy, resilience, good German (B2)', tr: 'Empati, dayanıklılık, iyi Almanca (B2)' },
    duties: { ar: 'رعاية المرضى، توثيق العلاج، مساعدة الأطباء', de: 'Patienten betreuen, Behandlung dokumentieren, Ärzten assistieren', en: 'Caring for patients, documenting treatment, assisting doctors', tr: 'Hasta bakımı, tedavi dokümantasyonu, doktorlara asistanlık' },
    skillsRequired: { ar: 'رعاية طبية، تواصل، تنظيم', de: 'Medizinische Pflege, Kommunikation, Organisation', en: 'Medical care, communication, organization', tr: 'Tıbbi bakım, iletişim, organizasyon' }
  }
];